#!/usr/bin/env Rscript

#Burden normalization

# Use control strains and no-burden peak to normalize between many plates

library(tidyverse)
library(ggplot2)
library(cowplot)

#debug
#input.file.string="02-output-all-merged/minOD_0.08_maxmethod_2_fit2pts_F_timeptdelta_2.csv"
#output.base.name="04-normalization/test"
#control.strains = c("JEB1204","JEB1205","JEB1206","JEB1207","JEB1208")
#metadata.file.string = "igem2019_experiment_tracker.csv"

if (!exists("input.file.string")) {
   suppressMessages(library(optparse))
   
   option_list = list(
      make_option(
         c("-i", "--input"), type="character", default=NULL, 
                  help="Input merged CSV file generated by burden_merge.R script.", metavar="merged.csv"
                  ),
      make_option(   
         c("-o", "--output"), type="character", default=NULL, 
      help="Output base name.", metavar="output"
      ),
      make_option(
         c("-m", "--metadata"), type="character", default=NULL, 
                  help="CSV file containing one line per plate analyzed that controls which plates are included in the overall analysis. This file must have columns: 'plate' and 'include'.", metavar="plate_metadata.csv"
                  ),
      make_option(
         c("-c", "--controls"), type="character", default=NULL, 
         help="Comma-separated list of control strains that will be used for normalization.", metavar="XX01,XX02,XX03"
      )
   )
   
   usage_string = paste(
      "burden_normalize.R -i merged.csv -o output -m metadata.csv -c XX01,XX02,XX03\n\n",
      sep = ""
   ) 
   
   opt_parser = OptionParser(usage=usage_string, option_list=option_list)
   opt = parse_args(opt_parser)
   
   if (is.null(opt$input) || is.null(opt$output) || is.null(opt$metadata) || is.null(opt$controls)) {
      print_help(opt_parser)
      stop("You must supply the -i, -o, -m, and -c arguments", call.=FALSE)
   }
   
   input.file.string = opt$input
   output.base.name = opt$output
   metadata.file.string = opt$metadata
   control.strains = as.vector(strsplit(opt$controls, ",")[[1]])
}

cat("Normalizing across different plates...\n")
cat("Input file of merged plates:  ", input.file.string, "\n")
cat("Input file of plate metadata: ", metadata.file.string, "\n")
cat("Output base name: ", output.base.name, "\n")
cat("Control strains:", paste0(control.strains, collapse=","), "\n")

##############  Read in the input files

all.data = read.csv(input.file.string)
all.data$plate.strain = paste0(all.data$plate, "_", all.data$strain)

############## Subset to the plates that we want to include

metadata = read.csv(metadata.file.string)
include.plates = (metadata %>% filter(include==T))$plate

all.data = all.data %>% filter(plate %in% include.plates)
all.data$plate = droplevels(all.data$plate)

##############  Make a general QC graph that highlights the controls
control.data=all.data %>% filter(strain %in% control.strains)
not.control.data = all.data %>% filter(!(strain %in% control.strains))


p = ggplot(not.control.data , aes(x=plate, y=growth.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=control.data, width=0.2, size=1, aes(x=plate, y=growth.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0.4,1.6)

ggsave(paste0(output.base.name,".growth-rate-unnormalized.pdf"), p)

p = ggplot(not.control.data , aes(x=plate, y=GFP.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=control.data, width=0.2, size=1, aes(x=plate, y=GFP.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(200,800)

ggsave(paste0(output.base.name,".GFP-rate-unnormalized.pdf"), p)


#Show control strains only
#ggplot(control.data, aes(x=plate, y=growth.rate, color=strain)) + geom_point()


no.burden.quantile = not.control.data %>% group_by(plate, strain) %>% summarize(growth.rate.mean=mean(growth.rate), GFP.rate.mean=mean(GFP.rate)) %>% group_by(plate) %>% summarize(growth.rate.quantile=quantile(growth.rate.mean, probs=0.8), GFP.rate.quantile=quantile(GFP.rate.mean, probs=0.8, na.rm=T))

##############  Make a  QC graph that connects the controls

control.data.means = control.data %>% group_by(plate, strain) %>% summarize(growth.rate.mean=mean(growth.rate), growth.rate.sd = sd(growth.rate), GFP.rate.mean=mean(GFP.rate), GFP.rate.sd = sd(GFP.rate))

p = ggplot(control.data.means, aes(x=plate, y=growth.rate.mean, color=strain)) + 
   geom_jitter(data=control.data, width=0.2, size=1, aes(x=plate, y=growth.rate, color=strain)) +
   geom_line(data=control.data.means, aes(x=plate, y=growth.rate.mean, color=strain, group=strain)) +
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   #geom_errorbar(aes(ymin=growth.rate.mean-growth.rate.sd, ymax=growth.rate.mean+growth.rate.sd), width=.2,) +
   geom_point(data=no.burden.quantile, aes(x=plate, y=growth.rate.quantile, group="new"), color="black")

ggsave(paste0(output.base.name,".growth-unnormalized-rate-control-mean-and-q80.pdf"), p)

p = ggplot(control.data.means, aes(x=plate, y=GFP.rate.mean, color=strain)) + 
   geom_jitter(data=control.data, width=0.2, size=1, aes(x=plate, y=GFP.rate, color=strain)) +
   geom_line(data=control.data.means, aes(x=plate, y=GFP.rate.mean, color=strain, group=strain)) +
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
#   geom_errorbar(aes(ymin=GFP.rate.mean-GFP.rate.sd, ymax=GFP.rate.mean+GFP.rate.sd), width=0.2) +
   geom_point(data=no.burden.quantile, aes(x=plate, y=GFP.rate.quantile, group="new"), color="black")

ggsave(paste0(output.base.name,".GFP-rate-unnormalized-control-mean-and-q80.pdf"), p)



##############  Determine the no-burden growth rate for each run 
##############  by looking for the maximum density of points

metadata = metadata %>% filter(plate %in% include.plates)
droplevels(metadata$plate)

metadata$no.burden.growth.rate = c()
metadata$no.burden.GFP.rate = c()

for (i in 1:nrow(metadata)) {
   this.plate = as.character(metadata$plate[i])
   plate.no.control.data = not.control.data %>% filter(plate==this.plate)
   
   this.density = density(plate.no.control.data$growth.rate)
   max.y.index = which.max(this.density$y)
   no.burden.growth.rate = this.density$x[max.y.index]
   
   ggplot(plate.no.control.data, aes(x=growth.rate)) + 
      geom_density() + scale_x_continuous(breaks = seq(0, 2, by = 0.1), limits=c(0,2)) + geom_vline(xintercept=no.burden.growth.rate) 
   
   metadata$no.burden.growth.rate[i] = no.burden.growth.rate
   
   #Remove some that have no GFP measurements
   plate.no.control.data.has.GFP = plate.no.control.data %>% filter(!is.na(GFP.rate))
   
   this.density = density(plate.no.control.data.has.GFP$GFP.rate)
   max.y.index = which.max(this.density$y)
   no.burden.GFP.rate = this.density$x[max.y.index]
   
   ggplot(plate.no.control.data.has.GFP, aes(x=GFP.rate)) + 
      geom_density() + scale_x_continuous(breaks = seq(200, 800, by = 50), limits=c(200,800)) + geom_vline(xintercept=no.burden.GFP.rate) 
   
   metadata$no.burden.GFP.rate[i] = no.burden.GFP.rate
}


## Normalize to the no.burden.growth.rate
no.burden.growth.rate.data = data.frame(plate=as.character(metadata$plate), no.burden.growth.rate = metadata$no.burden.growth.rate, no.burden.GFP.rate = metadata$no.burden.GFP.rate)

no.burden.normalized.data = all.data %>% left_join(no.burden.growth.rate.data, by="plate")
no.burden.normalized.data$normalized.growth.rate = no.burden.normalized.data$growth.rate / no.burden.normalized.data$no.burden.growth.rate
no.burden.normalized.data$normalized.GFP.rate = no.burden.normalized.data$GFP.rate / no.burden.normalized.data$no.burden.GFP.rate


no.burden.normalized.control.data = no.burden.normalized.data %>% filter(strain %in% control.strains)
no.burden.normalized.not.control.data = no.burden.normalized.data %>% filter(!(strain %in% control.strains))

p = ggplot(no.burden.normalized.not.control.data , aes(x=plate, y=normalized.growth.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=no.burden.normalized.control.data, width=0.2, size=1, aes(x=plate, y=normalized.growth.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0.4,1.2)

ggsave(paste0(output.base.name,".growth-rate-no-burden-normalized.pdf"), p)

p = ggplot(no.burden.normalized.not.control.data , aes(x=plate, y=normalized.GFP.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=no.burden.normalized.control.data, width=0.2, size=1, aes(x=plate, y=normalized.GFP.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0.2,1.4)

ggsave(paste0(output.base.name,".GFP-rate-no-burden-normalized.pdf"), p)




##############  Further normalize values between runs based on controls. 


## determine the grand means for the controls across all plates

control.means = no.burden.normalized.control.data %>% group_by(strain) %>% summarize(normalized.growth.rate.grand.mean=mean(normalized.growth.rate), normalized.GFP.rate.grand.mean=mean(normalized.GFP.rate))

#now fit the best line going through 1,1 for each run individually

adjustments = data.frame()
for (this.plate in unique(all.data$plate)) {
   
   this.normalized.control.data.means = no.burden.normalized.data %>% filter(plate==this.plate)

   this.normalized.control.data.means = this.normalized.control.data.means %>% left_join(control.means, by="strain")
   
   to.fit = this.normalized.control.data.means %>% select(normalized.growth.rate, normalized.growth.rate.grand.mean, normalized.GFP.rate, normalized.GFP.rate.grand.mean)
   
   to.fit$normalized.growth.rate = 1-to.fit$normalized.growth.rate
   to.fit$normalized.growth.rate.grand.mean = 1-to.fit$normalized.growth.rate.grand.mean
   
   to.fit$normalized.GFP.rate = 1-to.fit$normalized.GFP.rate
   to.fit$normalized.GFP.rate.grand.mean = 1-to.fit$normalized.GFP.rate.grand.mean
   
   the.growth.rate.fit = lm(normalized.growth.rate.grand.mean~normalized.growth.rate+0, data=to.fit
)
   the.GFP.rate.fit = lm(normalized.GFP.rate.grand.mean~normalized.GFP.rate+0, data=to.fit)
                
   adjustments = bind_rows(adjustments, data.frame(plate=this.plate, growth.rate.normalization.factor = coef(the.growth.rate.fit)[1], GFP.rate.normalization.factor = coef(the.GFP.rate.fit)[1]))
}

final.normalized.data = no.burden.normalized.data

final.normalized.data = final.normalized.data %>% left_join(adjustments, by="plate")

final.normalized.data$normalized.growth.rate = 1-(1-final.normalized.data$normalized.growth.rate)*final.normalized.data$growth.rate.normalization.factor
final.normalized.data$normalized.GFP.rate = 1-(1-final.normalized.data$normalized.GFP.rate)*final.normalized.data$GFP.rate.normalization.factor

final.normalized.control.data=final.normalized.data %>% filter(strain %in% control.strains)
final.normalized.not.control.data = final.normalized.data %>% filter(!(strain %in% control.strains))

p = ggplot(final.normalized.not.control.data , aes(x=plate, y=normalized.growth.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=final.normalized.control.data, width=0.2, size=1, aes(x=plate, y=normalized.growth.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0.4,1.2)

ggsave(paste0(output.base.name,".growth-rate-no-burden-and-control-normalized.pdf"), p)

p = ggplot(final.normalized.not.control.data , aes(x=plate, y=normalized.GFP.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=final.normalized.control.data, width=0.2, size=1, aes(x=plate, y=normalized.GFP.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0.4,1.2)

ggsave(paste0(output.base.name,".GFP-rate-no-burden-and-control-normalized.pdf"), p)


##################################

#Now judge which are significantly different from one

parts = final.normalized.not.control.data
significant.ones = c()
p.values = data.frame()
number.of.tests = length(unique(parts$plate.strain))
for (this.plate.strain in unique(parts$plate.strain)) {

   this.strain.plate.data = parts %>% filter(plate.strain == this.plate.strain)
   
   cat(this.plate.strain, "  ", length(this.strain.plate.data$normalized.growth.rate), "\n")
   
   if (length(this.strain.plate.data$normalized.growth.rate) > 1) {
   
   test.result = t.test(this.strain.plate.data$normalized.growth.rate-1, alternative = "less")
   cat(this.plate.strain, "  ", test.result$p.value, "\n")
   if (test.result$p.value < 0.05) {
      significant.ones = c(significant.ones, this.plate.strain)
   }
   } else {
      test.result = data.frame(p.value=NA)
   }
   
   p.values = bind_rows(p.values, data.frame(plate.strain=this.plate.strain, p.value = test.result$p.value ))
}
p.values$adj.p.value = p.adjust(p.values$p.value, method="BH")

parts = final.normalized.not.control.data
translational.burden.fraction.p.values = data.frame()
for (this.plate.strain in unique(parts$plate.strain)) {
   
   this.strain.plate.data = parts %>% filter(plate.strain == this.plate.strain) %>% filter(!is.na(normalized.GFP.rate))
   
   cat(this.plate.strain, "  ", length(this.strain.plate.data$normalized.GFP.rate), "\n")
   
   if ( (length(this.strain.plate.data$normalized.GFP.rate) > 1)) {
      
      test.result = t.test(this.strain.plate.data$normalized.GFP.rate, this.strain.plate.data$normalized.growth.rate, alternative = "greater")
      cat(this.plate.strain, "  ", test.result$p.value, "\n")
   } else {
      test.result = data.frame(p.value=NA)
   }
   translational.burden.fraction.p.values = bind_rows(translational.burden.fraction.p.values, data.frame(plate.strain=this.plate.strain, translational.burden.fraction.p.value = test.result$p.value ))
}
translational.burden.fraction.p.values$translational.burden.fraction.adj.p.value = p.adjust(translational.burden.fraction.p.values$translational.burden.fraction.p.value, method="BH")

parts = final.normalized.data


parts.means = parts %>% group_by(plate, strain, plate.strain) %>% summarize(replicates=n(), normalized.growth.rate.mean=mean(normalized.growth.rate), normalized.growth.rate.sd=sd(normalized.growth.rate), normalized.growth.rate.cv=sd(normalized.growth.rate)/mean(normalized.growth.rate), normalized.growth.rate.sem = normalized.growth.rate.sd/sqrt(replicates), normalized.growth.rate.95CI.range =  normalized.growth.rate.sem*qt(0.975, df=replicates-1), normalized.GFP.rate.mean=mean(normalized.GFP.rate), normalized.GFP.rate.sd=sd(normalized.GFP.rate), normalized.GFP.rate.sem = normalized.GFP.rate.sd/sqrt(replicates), normalized.GFP.rate.95CI.range =  normalized.GFP.rate.sem*qt(0.975, df=replicates-1))
parts.means = parts.means %>%left_join(p.values, by="plate.strain")
parts.means = parts.means %>%left_join(translational.burden.fraction.p.values, by="plate.strain")
parts.means = parts.means %>% group_by() %>% select(-plate.strain)

parts.means$category = c()
parts.means$category = "no burden";
parts.means$category[parts.means$p.value < 0.05] = "significant"
parts.means$category[parts.means$strain %in% control.strains] = "control"

parts.means$burden.mean = 1-parts.means$normalized.growth.rate.mean
parts.means$burden.sd = parts.means$normalized.growth.rate.sd
parts.means$burden.sem = parts.means$normalized.growth.rate.sem
parts.means$burden.95CI.range = parts.means$normalized.growth.rate.95CI.range
parts.means$burden.cv = parts.means$burden.sd  / parts.means$burden.mean

parts.means$translational.burden.fraction.mean =  (1 - parts.means$normalized.GFP.rate.mean) / (1 - parts.means$normalized.growth.rate.mean)
parts.means$translational.burden.fraction.sd = parts.means$normalized.GFP.rate.sd / (1 - parts.means$normalized.growth.rate.mean)
parts.means$translational.burden.fraction.sem = parts.means$normalized.growth.rate.sem / (1 - parts.means$normalized.growth.rate.mean)
parts.means$translational.burden.fraction.95CI.range = parts.means$normalized.growth.rate.95CI.range / (1 - parts.means$normalized.growth.rate.mean)

#parts.means = parts.means %>% select(-growth.rate.mean,-growth.rate.sd)

write.csv(parts.means, paste0(output.base.name, ".part_burden.csv"), row.names=F)





