#!/usr/bin/env Rscript

#Burden normalization

# Use control strains and no-burden peak to normalize between many plates

library(tidyverse)
library(ggplot2)
library(cowplot)

#debug
input.file.string="02b-output-all-merged/output.csv"
output.base.name="04-normalization/output"
plate.metadata.file.string = "igem2019_plate_metadata.csv"
strain.metadata.file.string = "igem2019_strain_metadata.csv"
control.strains = c("JEB1204","JEB1205","JEB1206","JEB1207","JEB1208")
included.vectors = c("pSB1C3","pSB1A2")

if (!exists("input.file.string")) {
   suppressMessages(library(optparse))
   
   option_list = list(
      make_option(
         c("-i", "--input"), type="character", default=NULL, 
                  help="Input merged CSV file generated by burden_merge.R script.", metavar="merged.csv"
                  ),
      make_option(   
         c("-o", "--output"), type="character", default=NULL, 
      help="Output base name.", metavar="output"
      ),
      make_option(
         c("-m", "--plate-metadata"), type="character", default=NULL, 
                  help="CSV file containing one line per plate analyzed that controls which plates are included in the overall analysis. This file must have columns: 'plate' and 'include'.", metavar="plate_metadata.csv"
                  ),
      make_option(
         c( "-s", "--strain-metadata"), type="character", default=NULL, 
                  help="CSV file containing one line per strain analyzed that controls which vectors are included in the overall analysis. This file must have columns: 'strain' and 'vector'", 
                  metavar="strain_metadata.csv"
      ),
      make_option(
         c("-c", "--controls"), type="character", default=NULL, 
         help="Comma-separated list of control strains that will be used for normalization.", metavar="XX01,XX02,XX03"
      ),
      make_option(
         c("-v", "--vectors"), type="character", default=NA, 
         help="Comma-separated list of vectors to include in dataset.", metavar="pSB1C3,pSB1A2"
      )
   )
   
   usage_string = paste(
      "burden_normalize.R -i merged.csv -o output -m metadata.csv -c XX01,XX02,XX03\n\n",
      sep = ""
   ) 
   
   opt_parser = OptionParser(usage=usage_string, option_list=option_list)
   opt = parse_args(opt_parser)
   
   if (is.null(opt$input) || is.null(opt$output) || is.null(opt$'plate-metadata') || is.null(opt$controls)) {
      print_help(opt_parser)
      stop("You must supply the -i, -o, -m, and -c arguments", call.=FALSE)
   }
   
   input.file.string = opt$input
   output.base.name = opt$output
   plate.metadata.file.string = opt$'plate-metadata'
   strain.metadata.file.string = opt$'strain-metadata'
   control.strains = as.vector(strsplit(opt$controls, ",")[[1]])
   included.vectors = c()
   if (!is.na(opt$vectors)) {
      included.vectors = as.vector(strsplit(opt$vectors, ",")[[1]])
   }
}

cat("Normalizing across different plates...\n")
cat("Input file of merged plates:  ", input.file.string, "\n")
cat("Input file of plate metadata: ", plate.metadata.file.string, "\n")
cat("Input file of strain metadata: ", strain.metadata.file.string, "\n")
cat("Output base name: ", output.base.name, "\n")
cat("Control strains:", paste0(control.strains, collapse=","), "\n")
if (length(included.vectors)==0) {
   cat("Included vectors:", "all", "\n")
} else {
   cat("Included vectors:", paste0(included.vectors, collapse=","), "\n")
}

##############  Read in the input files

all.data = read.csv(input.file.string)
all.data$plate.strain = paste0(all.data$plate, "_", all.data$strain)

############## Subset to the plates that we want to include

plate.metadata = read.csv(plate.metadata.file.string)
include.plates = (plate.metadata %>% filter(include==T))$plate

all.data = all.data %>% filter(plate %in% include.plates)
all.data$plate = droplevels(all.data$plate)


############## Subset to the vectors that we want to include

cat("Input plates (before filtering):", length(unique(all.data$plate)), "\n")
cat("Analyzed strains (before filtering):", length(unique(all.data$strain)), "\n")

if (length(included.vectors)>0) {
   strain.metadata = read.csv(strain.metadata.file.string)
   strain.metadata.merge = strain.metadata %>% select(strain, vector, accession)
   all.data = all.data %>% left_join(strain.metadata.merge, by="strain")
   all.data = all.data %>% filter(vector %in% included.vectors)
   
   not.control.data = all.data %>% filter(!(strain %in% control.strains))
   num.not.control.per.plate = not.control.data %>% group_by(plate,strain) %>% summarize(n=n()) %>% group_by(plate) %>% summarize(n=n())
   
   #Remove empty plates - could remove ones with fewer than some number of strains
   all.data = all.data %>% filter(plate %in% unique(num.not.control.per.plate$plate))
   include.plates = unique(all.data$plate)
   all.data$plate = droplevels(all.data$plate)
}
cat("Analyzed plates (after filtering):", length(unique(all.data$plate)), length(unique(all.data$vector)), "\n")
cat("Analyzed strains (after filtering):", length(unique(all.data$strain)), "\n")

##############  Make a general QC graph that highlights the controls
control.data=all.data %>% filter(strain %in% control.strains)
not.control.data = all.data %>% filter(!(strain %in% control.strains))

# how many are left on each plate that are not controls?
num.not.control.per.plate = not.control.data %>% group_by(plate,strain) %>% summarize(n=n()) %>% group_by(plate) %>% summarize(n=n())

#filter out any that don't appear in num.not.control.per.plate

p = ggplot(not.control.data , aes(x=plate, y=growth.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=control.data, width=0.2, size=1, aes(x=plate, y=growth.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0,1.6)

ggsave(paste0(output.base.name,".growth-rate-unnormalized.pdf"), p)

p = ggplot(not.control.data , aes(x=plate, y=GFP.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=control.data, width=0.2, size=1, aes(x=plate, y=GFP.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0,50000)

ggsave(paste0(output.base.name,".GFP-rate-unnormalized.pdf"), p)


#Show control strains only
#ggplot(control.data, aes(x=plate, y=growth.rate, color=strain)) + geom_point()


no.burden.quantile = not.control.data %>% group_by(plate, strain) %>% summarize(growth.rate.mean=mean(growth.rate), GFP.rate.mean=mean(GFP.rate)) %>% group_by(plate) %>% summarize(growth.rate.quantile=quantile(growth.rate.mean, probs=0.8), GFP.rate.quantile=quantile(GFP.rate.mean, probs=0.8, na.rm=T))

##############  Make a  QC graph that connects the controls

control.data.means = control.data %>% group_by(plate, strain) %>% summarize(growth.rate.mean=mean(growth.rate), growth.rate.sd = sd(growth.rate), GFP.rate.mean=mean(GFP.rate), GFP.rate.sd = sd(GFP.rate))

p = ggplot(control.data.means, aes(x=plate, y=growth.rate.mean, color=strain)) + 
   geom_jitter(data=control.data, width=0.2, size=1, aes(x=plate, y=growth.rate, color=strain)) +
   geom_line(data=control.data.means, aes(x=plate, y=growth.rate.mean, color=strain, group=strain)) +
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   #geom_errorbar(aes(ymin=growth.rate.mean-growth.rate.sd, ymax=growth.rate.mean+growth.rate.sd), width=.2,) +
   geom_point(data=no.burden.quantile, aes(x=plate, y=growth.rate.quantile, group="new"), color="black")

ggsave(paste0(output.base.name,".growth-rate-unnormalized-control-mean-and-q80.pdf"), p)

p = ggplot(control.data.means, aes(x=plate, y=GFP.rate.mean, color=strain)) + 
   geom_jitter(data=control.data, width=0.2, size=1, aes(x=plate, y=GFP.rate, color=strain)) +
   geom_line(data=control.data.means, aes(x=plate, y=GFP.rate.mean, color=strain, group=strain)) +
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
#   geom_errorbar(aes(ymin=GFP.rate.mean-GFP.rate.sd, ymax=GFP.rate.mean+GFP.rate.sd), width=0.2) +
   geom_point(data=no.burden.quantile, aes(x=plate, y=GFP.rate.quantile, group="new"), color="black")

ggsave(paste0(output.base.name,".GFP-rate-unnormalized-control-mean-and-q80.pdf"), p)



##############  Determine the no-burden growth rate for each run 
##############  by looking for the maximum density of points

plate.metadata = plate.metadata %>% filter(plate %in% include.plates)
droplevels(plate.metadata$plate)

plate.metadata$no.burden.growth.rate = c()
plate.metadata$no.burden.GFP.rate = c()

normalize.stats = data.frame(
   plate=plate.metadata$plate, 
   growth.rate.no.burden=NA, 
   growth.rate.bandwidth=NA,
   GFP.rate.no.burden=NA,
   GFP.rate.bandwidth=NA
)

for (i in 1:nrow(plate.metadata)) {
   growth.rate.bw=0.05
   GFP.rate.bw=480
   #GFP.rate.bw=0.05
   
   this.plate = as.character(plate.metadata$plate[i])
   plate.no.control.data = not.control.data %>% filter(plate==this.plate)
   
   this.density = density(plate.no.control.data$growth.rate, bw=growth.rate.bw)
   max.y.index = which.max(this.density$y)
   no.burden.growth.rate = this.density$x[max.y.index]
   
   normalize.stats$growth.rate.no.burden[i] = no.burden.growth.rate
   normalize.stats$growth.rate.bandwidth[i] = growth.rate.bw

   p = ggplot(plate.no.control.data, aes(x=growth.rate)) + 
   geom_density(bw=growth.rate.bw) + 
      scale_x_continuous(breaks = seq(0, 2, by = 0.1), limits=c(0,2)) + geom_vline(xintercept=no.burden.growth.rate) 
   ggsave(paste0(output.base.name,".",this.plate,".growth-rate-density-plot.pdf"), p)
   
   plate.metadata$no.burden.growth.rate[i] = no.burden.growth.rate
   
   #Remove some that have no GFP measurements
   plate.no.control.data.has.GFP = plate.no.control.data %>% filter(!is.na(GFP.rate))
   
   this.density = density(plate.no.control.data.has.GFP$GFP.rate, bw=GFP.rate.bw)
   max.y.index = which.max(this.density$y)
   no.burden.GFP.rate = this.density$x[max.y.index]
   
   normalize.stats$GFP.rate.no.burden[i] = no.burden.GFP.rate
   normalize.stats$GFP.rate.bandwidth[i] = GFP.rate.bw
   
   p = ggplot(plate.no.control.data.has.GFP, aes(x=GFP.rate)) + 
      geom_density(bw=GFP.rate.bw) + 
      scale_x_continuous(breaks = seq(0,50000, by = 5000), limits=c(0,50000)) + 
      geom_vline(xintercept=no.burden.GFP.rate) 
   ggsave(paste0(output.base.name,".",this.plate,".GFP-rate-density-plot.pdf"), p)
   
   plate.metadata$no.burden.GFP.rate[i] = no.burden.GFP.rate
}

write.csv(normalize.stats, paste0(output.base.name, ".normalize_stats.csv"), row.names=F)


## Normalize to the no.burden.growth.rate
no.burden.growth.rate.data = data.frame(plate=as.character(plate.metadata$plate), no.burden.growth.rate = plate.metadata$no.burden.growth.rate, no.burden.GFP.rate = plate.metadata$no.burden.GFP.rate)

no.burden.normalized.data = all.data %>% left_join(no.burden.growth.rate.data, by="plate")
no.burden.normalized.data$normalized.growth.rate = no.burden.normalized.data$growth.rate / no.burden.normalized.data$no.burden.growth.rate
no.burden.normalized.data$normalized.GFP.rate = no.burden.normalized.data$GFP.rate / no.burden.normalized.data$no.burden.GFP.rate

no.burden.normalized.control.data = no.burden.normalized.data %>% filter(strain %in% control.strains)
no.burden.normalized.not.control.data = no.burden.normalized.data %>% filter(!(strain %in% control.strains))

p = ggplot(no.burden.normalized.not.control.data , aes(x=plate, y=normalized.growth.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=no.burden.normalized.control.data, width=0.2, size=1, aes(x=plate, y=normalized.growth.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0,1.4)

ggsave(paste0(output.base.name,".growth-rate-no-burden-normalized.pdf"), p)

p = ggplot(no.burden.normalized.not.control.data , aes(x=plate, y=normalized.GFP.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=no.burden.normalized.control.data, width=0.2, size=1, aes(x=plate, y=normalized.GFP.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0,1.4)

ggsave(paste0(output.base.name,".GFP-rate-no-burden-normalized.pdf"), p)





##############  Further normalize values between runs based on controls. 


## determine the grand means for the controls across all plates


control.means = no.burden.normalized.control.data %>% group_by(strain) %>% summarize(normalized.growth.rate.grand.mean=mean(normalized.growth.rate), normalized.GFP.rate.grand.mean=mean(normalized.GFP.rate))

## testing mean of mean to force slope closer to 1
#control.means$normalized.grand.mean.mean  = (control.means$normalized.growth.rate.grand.mean + control.means$normalized.GFP.rate.grand.mean)/2
#control.means$normalized.growth.rate.grand.mean = control.means$normalized.grand.mean.mean
#control.means$normalized.GFP.rate.grand.mean = control.means$normalized.grand.mean.mean

print(control.means)


#now fit the best line going through 1,1 for each run individually

adjustments = data.frame()
for (this.plate in unique(all.data$plate)) {
   
   this.normalized.control.data.means = no.burden.normalized.data %>% filter(plate==this.plate)

   this.normalized.control.data.means = this.normalized.control.data.means %>% left_join(control.means, by="strain")
   
   to.fit = this.normalized.control.data.means %>% select(normalized.growth.rate, normalized.growth.rate.grand.mean, normalized.GFP.rate, normalized.GFP.rate.grand.mean)
   
   to.fit$normalized.growth.rate = 1-to.fit$normalized.growth.rate
   to.fit$normalized.growth.rate.grand.mean = 1-to.fit$normalized.growth.rate.grand.mean
   
   to.fit$normalized.GFP.rate = 1-to.fit$normalized.GFP.rate
   to.fit$normalized.GFP.rate.grand.mean = 1-to.fit$normalized.GFP.rate.grand.mean
   
   the.growth.rate.fit = lm(normalized.growth.rate.grand.mean~normalized.growth.rate+0, data=to.fit
)
   the.GFP.rate.fit = lm(normalized.GFP.rate.grand.mean~normalized.GFP.rate+0, data=to.fit)
                
   adjustments = bind_rows(adjustments, data.frame(plate=this.plate, growth.rate.normalization.factor = coef(the.growth.rate.fit)[1], GFP.rate.normalization.factor = coef(the.GFP.rate.fit)[1]))
}

final.normalized.data = no.burden.normalized.data

final.normalized.data = final.normalized.data %>% left_join(adjustments, by="plate")

final.normalized.data$normalized.growth.rate = 1-(1-final.normalized.data$normalized.growth.rate)*final.normalized.data$growth.rate.normalization.factor
final.normalized.data$normalized.GFP.rate = 1-(1-final.normalized.data$normalized.GFP.rate)*final.normalized.data$GFP.rate.normalization.factor

#Output all normalized values
write.csv(final.normalized.data, paste0(output.base.name, ".normalized.burden.all.wells.csv"), row.names=F)


final.normalized.control.data=final.normalized.data %>% filter(strain %in% control.strains)
final.normalized.not.control.data = final.normalized.data %>% filter(!(strain %in% control.strains))

p = ggplot(final.normalized.not.control.data , aes(x=plate, y=normalized.growth.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=final.normalized.control.data, width=0.2, size=1, aes(x=plate, y=normalized.growth.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0.4,1.2)

ggsave(paste0(output.base.name,".growth-rate-no-burden-and-control-normalized.pdf"), p)

p = ggplot(final.normalized.not.control.data , aes(x=plate, y=normalized.GFP.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=final.normalized.control.data, width=0.2, size=1, aes(x=plate, y=normalized.GFP.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0.4,1.2)

ggsave(paste0(output.base.name,".GFP-rate-no-burden-and-control-normalized.pdf"), p)


########################################################################################
### File for performing stats while keeping unique plate-strain combinations

parts = final.normalized.not.control.data
p.values = data.frame()
for (this.plate.strain in unique(parts$plate.strain)) {
   
   this.strain.plate.data = parts %>% filter(plate.strain == this.plate.strain)
   
   #cat(this.plate.strain, "  ", length(this.strain.plate.data$normalized.growth.rate), "\n")
   
   if (length(this.strain.plate.data$normalized.growth.rate) > 1) {
      test.result = t.test(this.strain.plate.data$normalized.growth.rate-1, alternative = "less")
   } else {
      test.result = data.frame(p.value=NA)
   }
   
   p.values = bind_rows(p.values, data.frame(plate.strain=this.plate.strain, growth.rate.reduced.p.value = test.result$p.value ))
}
p.values$growth.rate.reduced.adj.p.value = p.adjust(p.values$growth.rate.reduced.p.value, method="BH")

parts = final.normalized.data

parts.means = parts %>% group_by(plate, strain, plate.strain) %>% summarize(replicates=n(), normalized.growth.rate.mean=mean(normalized.growth.rate), normalized.growth.rate.sd=sd(normalized.growth.rate), normalized.growth.rate.cv=sd(normalized.growth.rate)/mean(normalized.growth.rate), normalized.growth.rate.sem = normalized.growth.rate.sd/sqrt(replicates), normalized.growth.rate.95CI.range =  normalized.growth.rate.sem*qt(0.975, df=replicates-1), normalized.GFP.rate.mean=mean(normalized.GFP.rate), normalized.GFP.rate.sd=sd(normalized.GFP.rate), normalized.GFP.rate.cv=sd(normalized.GFP.rate)/mean(normalized.GFP.rate), normalized.GFP.rate.sem = normalized.GFP.rate.sd/sqrt(replicates), normalized.GFP.rate.95CI.range =  normalized.GFP.rate.sem*qt(0.975, df=replicates-1))
parts.means = parts.means %>%left_join(p.values, by="plate.strain")
#parts.means = parts.means %>%left_join(translational.burden.fraction.p.values, by="plate.strain")
parts.means = parts.means %>% group_by() %>% select(-plate.strain)

parts.means$burden.category = c()
parts.means$burden.category = "no burden";
parts.means$burden.category[parts.means$growth.rate.reduced.adj.p.value < 0.05] = "significant"
parts.means$burden.category[parts.means$strain %in% control.strains] = "control"

parts.means$burden.mean = 1-parts.means$normalized.growth.rate.mean
parts.means$burden.sd = parts.means$normalized.growth.rate.sd
parts.means$burden.sem = parts.means$normalized.growth.rate.sem
parts.means$burden.95CI.range = parts.means$normalized.growth.rate.95CI.range
parts.means$burden.cv = parts.means$burden.sd  / parts.means$burden.mean

write.csv(parts.means, paste0(output.base.name, ".plate-strain.burden.csv"), row.names=F)

########################################################################################
### File for performing stats that only keeps one entry for each strain
### (That is, it combines data for a strain across different plates)

parts = final.normalized.not.control.data

p.values = data.frame()
for (this.strain in unique(parts$strain)) {
   
   this.strain.data = parts %>% filter(strain == this.strain)
   
   #cat(this.plate.strain, "  ", length(this.strain.plate.data$normalized.growth.rate), "\n")
   
   if (length(this.strain.data$normalized.growth.rate) > 1) {
      
      test.result = t.test(this.strain.data$normalized.growth.rate-1, alternative = "less")
      #cat(this.plate.strain, "  ", test.result$p.value, "\n")

   } else {
      test.result = data.frame(p.value=NA)
   }
   
   p.values = bind_rows(p.values, data.frame(strain=this.strain, growth.rate.reduced.p.value = test.result$p.value ))
}
p.values$growth.rate.reduced.adj.p.value = p.adjust(p.values$growth.rate.reduced.p.value, method="BH")

parts = final.normalized.data

parts.means = parts %>% group_by(strain) %>% summarize(replicates=n(), normalized.growth.rate.mean=mean(normalized.growth.rate), normalized.growth.rate.sd=sd(normalized.growth.rate), normalized.growth.rate.cv=sd(normalized.growth.rate)/mean(normalized.growth.rate), normalized.growth.rate.sem = normalized.growth.rate.sd/sqrt(replicates), normalized.growth.rate.95CI.range =  normalized.growth.rate.sem*qt(0.975, df=replicates-1), normalized.GFP.rate.mean=mean(normalized.GFP.rate), normalized.GFP.rate.sd=sd(normalized.GFP.rate), normalized.GFP.rate.cv=sd(normalized.GFP.rate)/mean(normalized.GFP.rate), normalized.GFP.rate.sem = normalized.GFP.rate.sd/sqrt(replicates), normalized.GFP.rate.95CI.range = normalized.GFP.rate.sem*qt(0.975, df=replicates-1), plates=paste(unique(plate), collapse=","), vector=paste(unique(vector), collapse=","), accession=paste(unique(accession), collapse=","))
parts.means = parts.means %>%left_join(p.values, by="strain")

parts.means = parts.means %>% group_by()

parts.means$burden.category = c()
parts.means$burden.category = "no burden";
parts.means$burden.category[parts.means$growth.rate.reduced.adj.p.value < 0.05] = "significant"
parts.means$burden.category[parts.means$strain %in% control.strains] = "control"

parts.means$burden.mean = 1-parts.means$normalized.growth.rate.mean
parts.means$burden.sd = parts.means$normalized.growth.rate.sd
parts.means$burden.sem = parts.means$normalized.growth.rate.sem
parts.means$burden.95CI.range = parts.means$normalized.growth.rate.95CI.range
parts.means$burden.cv = parts.means$burden.sd  / parts.means$burden.mean

write.csv(parts.means, paste0(output.base.name, ".strain.burden.csv"), row.names=F)





########################################################################################
### File for performing stats that only keeps one entry for each part
### (That is, it combines data for all strains with a part and across different plates)

parts = final.normalized.not.control.data
control.accessions = (strain.metadata %>% filter(strain %in% control.strains))$accession

p.values = data.frame()
for (this.accession in unique(parts$accession)) {
   
   this.accession.data = parts %>% filter(accession == this.accession)
   
   if (length(this.accession.data$normalized.growth.rate) > 1) {
      
      test.result = t.test(this.accession.data$normalized.growth.rate-1, alternative = "less")

   } else {
      test.result = data.frame(p.value=NA)
   }
   
   p.values = bind_rows(p.values, data.frame(accession=this.accession, growth.rate.reduced.p.value = test.result$p.value ))
}
p.values$growth.rate.reduced.adj.p.value = p.adjust(p.values$growth.rate.reduced.p.value, method="BH")

parts = final.normalized.data

parts.means = parts %>% group_by(accession) %>% summarize(replicates=n(), normalized.growth.rate.mean=mean(normalized.growth.rate), normalized.growth.rate.sd=sd(normalized.growth.rate), normalized.growth.rate.cv=sd(normalized.growth.rate)/mean(normalized.growth.rate), normalized.growth.rate.sem = normalized.growth.rate.sd/sqrt(replicates), normalized.growth.rate.95CI.range =  normalized.growth.rate.sem*qt(0.975, df=replicates-1), normalized.GFP.rate.mean=mean(normalized.GFP.rate), normalized.GFP.rate.sd=sd(normalized.GFP.rate), normalized.GFP.rate.cv=sd(normalized.GFP.rate)/mean(normalized.GFP.rate), normalized.GFP.rate.sem = normalized.GFP.rate.sd/sqrt(replicates), normalized.GFP.rate.95CI.range = normalized.GFP.rate.sem*qt(0.975, df=replicates-1), plates=paste(sort(unique(plate)), collapse=","), strains=paste(sort(unique(strain)), collapse=","), strain=unique(strain)[1], vectors=paste(sort(unique(vector)), collapse=","))

parts.means = parts.means %>%left_join(p.values, by="accession")

parts.means = parts.means %>% group_by()

parts.means$burden.category = c()
parts.means$burden.category = "no burden";
parts.means$burden.category[parts.means$growth.rate.reduced.adj.p.value < 0.05] = "significant"
parts.means$burden.category[parts.means$accession %in% control.accessions] = "control"

parts.means$burden.mean = 1-parts.means$normalized.growth.rate.mean
parts.means$burden.sd = parts.means$normalized.growth.rate.sd
parts.means$burden.sem = parts.means$normalized.growth.rate.sem
parts.means$burden.95CI.range = parts.means$normalized.growth.rate.95CI.range
parts.means$burden.cv = parts.means$burden.sd  / parts.means$burden.mean

write.csv(parts.means, paste0(output.base.name, ".part.burden.csv"), row.names=F)

