#!/usr/bin/env Rscript

#igem2019 specific analyses

library(tidyverse)
library(ggplot2)
library(cowplot)

#debug
input.file.string="04-normalization/minOD_0.08_maxmethod_2_fit2pts_F_timeptdelta_2.part_burden.csv"
output.base.name="04-normalization/test"
control.strains = c("JEB1204","JEB1205","JEB1206","JEB1207","JEB1208")
metadata.file.string = "igem2019_plate_metadata.csv"

if (!exists("input.file.string")) {
   suppressMessages(library(optparse))
   
   option_list = list(
      make_option(
         c("-i", "--input"), type="character", default=NULL, 
         help="Input normalized CSV file generated by burden_normalize.R script.", metavar="normalized.csv"
      ),
      make_option(   
         c("-o", "--output"), type="character", default=NULL, 
         help="Output base name.", metavar="output"
      ),
      make_option(
         c("-m", "--metadata"), type="character", default=NULL, 
         help="CSV file containing one line per strain analyzed.", metavar="strain_metadata.csv"
      ),
      make_option(
         c("-c", "--controls"), type="character", default=NULL, 
         help="Comma-separated list of control strains that will be used for normalization.", metavar="XX01,XX02,XX03"
      )
   )
   
   usage_string = paste(
      "burden_normalize.R -i merged.csv -o output -m metadata.csv -c XX01,XX02,XX03\n\n",
      sep = ""
   ) 
   
   opt_parser = OptionParser(usage=usage_string, option_list=option_list)
   opt = parse_args(opt_parser)
   
   if (is.null(opt$input) || is.null(opt$output) || is.null(opt$metadata) || is.null(opt$controls)) {
      print_help(opt_parser)
      stop("You must supply the -i, -o, -m, and -c arguments", call.=FALSE)
   }
   
   input.file.string = opt$input
   output.base.name = opt$output
   metadata.file.string = opt$metadata
   control.strains = as.vector(strsplit(opt$controls, ",")[[1]])
}

cat("Normalizing across different plates...\n")
cat("Input file of normalized values:  ", input.file.string, "\n")
cat("Input file of strain metadata: ", metadata.file.string, "\n")
cat("Output base name: ", output.base.name, "\n")
cat("Control strains:", paste0(control.strains, collapse=","), "\n")


##############  Read in the input files

all.data = read.csv(input.file.string)
all.data$experiment.strain = paste0(all.data$experiment, "_", all.data$strain)


### Plot testing for trend in coefficient of variation versus growth rate

non.control.parts.means = all.data %>% filter(category != "control")


non.control.parts.means = non.control.parts.means %>% filter(normalized.growth.rate.mean>0.5) %>% filter(normalized.growth.rate.cv<0.2)

ggplot(non.control.parts.means, aes(x=normalized.growth.rate.mean, y=normalized.growth.rate.cv, color=category)) + geom_point() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + geom_smooth(data=non.control.parts.means, aes(x=normalized.growth.rate.mean, y=normalized.growth.rate.cv), method = "lm", se = FALSE, inherit.aes=F)

fit = lm(normalized.growth.rate.mean~normalized.growth.rate.cv, data=non.control.parts.means)

cat("Is there a trend in the coefficient of variation such that smaller values have a higher coefficient of variation?\n")
summary(fit)

### Plot showing points colored by significance

p = ggplot(all.data, aes(x=plate, y=normalized.growth.rate.mean, color=category)) + geom_jitter() + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

ggsave(paste0(output.base.name, ".growth-rate-normalized-colored-by-significance.pdf"), p)

# Distribution plot showing where the controls end up

control.means = all.data %>% filter(category=="control") %>% group_by(strain) %>% summarize(normalized.growth.rate.grand.mean=mean(normalized.growth.rate.mean), normalized.GFP.rate.grand.mean=mean(normalized.GFP.rate.mean))

control.burdens = control.means
control.burdens$burden.mean = 1 - control.burdens$normalized.growth.rate.grand.mean
control.burdens = control.burdens %>% select(-normalized.growth.rate.grand.mean, -normalized.GFP.rate.grand.mean)
control.burdens = rbind(data.frame(strain="no burden", burden.mean=0), control.burdens)

p = ggplot(all.data %>% filter(category!="control"), aes(x=burden.mean)) + geom_density(bw=0.01) + xlim(-0.4, 0.6) + geom_vline(data = control.burdens, aes(xintercept=burden.mean, color=strain)) 
ggsave(paste0(output.base.name, ".burden-normalized-distribution.pdf"), p)


control.burdens = control.means
control.burdens$GFP.rate.mean = 1 - control.burdens$normalized.GFP.rate.grand.mean
control.burdens = control.burdens %>% select(-normalized.growth.rate.grand.mean, -normalized.GFP.rate.grand.mean)
control.burdens = rbind(data.frame(strain="no burden", GFP.rate.mean=0), control.burdens)

p = ggplot(all.data %>% filter(category!="control"), aes(x=1-normalized.GFP.rate.mean)) + geom_density(bw=0.01) + xlim(-0.4, 0.6) + geom_vline(data = control.burdens, aes(xintercept=GFP.rate.mean, color=strain)) 
ggsave(paste0(output.base.name, ".GFP-rate-normalized-distribution.pdf"), p)





############## Subset to the experiments that we want to include

metadata = read.csv("igem_2019_experiment_tracker.csv")
include.experiments = (metadata %>% filter(Include==T))$Experiment

all.data = all.data %>% filter(experiment %in% include.experiments)
all.data$experiment = droplevels(all.data$experiment)

all.data = all.data %>% filter(replicates>1)

all.data = all.data %>% filter(burden.cv<2)


##############  Make a general graph showing all of the points
control.data=all.data %>% filter(strain %in% c("JEB1204", "JEB1205", "JEB1206", "JEB1207", "JEB1208"))
not.control.data = all.data %>% filter(!(strain %in% c("JEB1204", "JEB1205", "JEB1206", "JEB1207", "JEB1208")))

min.plot.coord = 0.4
max.plot.coord = 1.4

ggplot(all.data , aes(x=normalized.growth.rate.mean, y=normalized.GFP.rate.mean, color=category)) + 
   geom_point() + coord_cartesian(xlim = c(min.plot.coord, max.plot.coord ), ylim = c(min.plot.coord, max.plot.coord)) + geom_abline(intercept = 0, slope = 1) +
   geom_errorbarh(aes(xmin=normalized.growth.rate.mean-normalized.growth.rate.sd, xmax=normalized.growth.rate.mean+normalized.growth.rate.sd, height=0.01)) +
   geom_errorbar(aes(ymin=normalized.GFP.rate.mean-normalized.GFP.rate.sd, ymax=normalized.GFP.rate.mean+normalized.GFP.rate.sd, width=0.01))

   

# What is the fit slope for the controls?
fit1 = lm(normalized.GFP.rate.mean ~ normalized.growth.rate.mean, all.data %>% filter(category=="control"))
fit2 = lm(normalized.GFP.rate.mean ~ normalized.growth.rate.mean + 0, all.data %>% filter(category=="control"))
anova(fit1, fit2)

## It's 1! With y-intercept not distinguishable from 0!

##### Analyze the replicate runs
plot_with_error_bars <- function(in.data) {
   
   ggplot(in.data , aes(x=normalized.growth.rate.mean, y=normalized.GFP.rate.mean, color=strain, shape=experiment)) + 
      geom_point(size=2) + 
      coord_cartesian(xlim = c(min.plot.coord, max.plot.coord ), ylim = c(min.plot.coord, max.plot.coord)) + 
      geom_abline(intercept = 0, slope = 1) +
      geom_errorbarh(aes(xmin=normalized.growth.rate.mean-normalized.growth.rate.sd, xmax=normalized.growth.rate.mean+normalized.growth.rate.sd, height=0.01)) +
      geom_errorbar(aes(ymin=normalized.GFP.rate.mean-normalized.GFP.rate.sd, ymax=normalized.GFP.rate.mean+normalized.GFP.rate.sd, width=0.01))
}


in.data=all.data %>% filter (experiment %in% c("exp003", "exp005"))

in.data=all.data %>% filter (experiment %in% c("exp050", "exp054"))

#RFP Strains
in.data=all.data %>% filter (experiment %in% c("exp045")) %>% filter (!category %in% c("control"))





