#!/usr/bin/env Rscript

#Burden normalization

# Use control strains and no-burden peak to normalize between many plates

library(tidyverse)
library(ggplot2)
library(cowplot)
library(deming)

#debug
if (F) {
   input.file.string="02b-output-all-merged/output.csv"
   output.base.name="04-normalization/output"
   plate.metadata.file.string = "igem2019_plate_metadata.csv"
   strain.metadata.file.string = "igem2019_strain_metadata.csv"
   control.strains = c("JEB1204","JEB1205","JEB1206","JEB1207","JEB1208")
   included.vectors = c("pSB1C3","pSB1A2")
   control.fitting.excluded.plates = c()
   control.only.normalization.plates = c()
}

# Define these in case we aren't using options
growth.rate.bw = NA
GFP.rate.bw = NA

if (!exists("input.file.string")) {
   suppressMessages(library(optparse))
   
   option_list = list(
      make_option(
         c("-i", "--input"), type="character", default=NULL, 
                  help="Input merged CSV file generated by burden_merge.R script.", metavar="merged.csv"
                  ),
      make_option(   
         c("-o", "--output"), type="character", default=NULL, 
      help="Output base name.", metavar="output"
      ),
      make_option(
         c("-m", "--plate-metadata"), type="character", default=NULL, 
                  help="CSV file containing one line per plate analyzed that controls which plates are included in the overall analysis. This file must have columns: 'plate' and 'include'.", metavar="plate_metadata.csv"
                  ),
      make_option(
         c( "-s", "--strain-metadata"), type="character", default=NULL, 
                  help="CSV file containing one line per strain analyzed that controls which vectors are included in the overall analysis. This file must have columns: 'strain' and 'vector'", 
                  metavar="strain_metadata.csv"
      ),
      make_option(
         c("-c", "--controls"), type="character", default=NULL, 
         help="Comma-separated list of control strains that will be used for normalization.", metavar="XX01,XX02,XX03"
      ),
      make_option(
         c("-v", "--vectors"), type="character", default=NA, 
         help="Comma-separated list of vectors to include in dataset.", metavar="pSB1C3,pSB1A2"
      ),
      make_option(
         c("-x", "--control-fitting-excluded-plates"), type="character", default=NA, 
         help="Comma-separated list of plates to exclude when calculating which plates have controls that will be used to normalize to (plates will still be normalized)", metavar="exp11,exp99"
      ),
      make_option(
         c("-n", "--control-only-normalization-plates"), type="character", default=NA, 
         help="Plates that will be normalized only to control strains, not also assuming the greatest density has no-burden", metavar="exp11,exp99"
      ),
      make_option(
         c("-z", "--no-control-normalization"), type="logical", action="store_true", 
         help="Plates that will be normalized only to control strains, not also assuming the greatest density has no-burden"
      ),
      make_option(
         c("--growth-rate-bw"), type="numeric", default=NA, 
         help="Bandwidth to use for smoothing the growth rate distribution to identify the no-burden peak used for normalization. If not specified, it will be predicted from the data."
      ),
      make_option(
         c("--GFP-rate-bw"), type="numeric", default=NA, 
         help="Bandwidth to use for smoothing the GFP rate distribution to identify no-burden peak used for normalization. If not specified, it will be predicted from the data."
      )
   )
   
   usage_string = paste(
      "burden_normalize.R -i merged.csv -o output -m metadata.csv -c XX01,XX02,XX03\n\n",
      sep = ""
   ) 
   
   opt_parser = OptionParser(usage=usage_string, option_list=option_list)
   opt = parse_args(opt_parser)
   
   if (is.null(opt$input) || is.null(opt$output) || is.null(opt$'plate-metadata') || is.null(opt$controls)) {
      print_help(opt_parser)
      stop("You must supply the -i, -o, -m, and -c arguments", call.=FALSE)
   }
   
   input.file.string = opt$input
   output.base.name = opt$output
   plate.metadata.file.string = opt$'plate-metadata'
   strain.metadata.file.string = opt$'strain-metadata'
   control.strains = as.vector(strsplit(opt$controls, ",")[[1]])
   included.vectors = c()
   if (!is.na(opt$vectors)) {
      included.vectors = as.vector(strsplit(opt$vectors, ",")[[1]])
   }
   
   control.fitting.excluded.plates = c()
   if (!is.na(opt$'control-fitting-excluded-plates')) {
      control.fitting.excluded.plates = as.vector(strsplit(opt$'control-fitting-excluded-plates', ",")[[1]])
   }
   
   control.only.normalization.plates = c()
   if (!is.na(opt$'control-only-normalization-plates')) {
      control.only.normalization.plates = as.vector(strsplit(opt$'control-only-normalization-plates', ",")[[1]])
   }
   
   if (!is.null(opt$'no-control-normalization')) {
      no.control.normalization = opt$'no-control-normalization'
   }
   
   growth.rate.bw = opt$'growth-rate-bw'
   GFP.rate.bw = opt$'GFP-rate-bw'
}

if (!exists("no.control.normalization")) {
   no.control.normalization = F
}

cat("Normalizing across different plates...\n")
cat("Input file of merged plates:  ", input.file.string, "\n")
cat("Input file of plate metadata: ", plate.metadata.file.string, "\n")
cat("Input file of strain metadata: ", strain.metadata.file.string, "\n")
cat("Output base name: ", output.base.name, "\n")

if (no.control.normalization) {
   cat("Control normalization: DISABLED\n")
} else {
   cat("Control normalization: ENABLED\n")
}


cat("Control strains:", paste0(control.strains, collapse=","), "\n")
if (length(included.vectors)==0) {
   cat("Included vectors:", "all", "\n")
} else {
   cat("Included vectors:", paste0(included.vectors, collapse=","), "\n")
}

if (length(control.fitting.excluded.plates)==0) {
   cat("Plates excluded from control fitting:", "none", "\n")
} else {
   cat("Plates excluded from control fitting:", paste0(control.fitting.excluded.plates, collapse=","), "\n")
}

if (length(control.only.normalization.plates)==0) {
   cat("Plates only normalized to controls:", "none", "\n")
} else {
   cat("Plates only normalized to controls:", paste0(control.only.normalization.plates, collapse=","), "\n")
}

if (is.na(growth.rate.bw)) {
   cat("Growth rate bandwidth: AUTO\n")
} else {
   cat("Growth rate bandwidth:", growth.rate.bw, "\n")
}

if (is.na(GFP.rate.bw)) {
   cat("GFP rate bandwidth: AUTO\n")
} else {
   cat("GFP rate bandwidth:", GFP.rate.bw, "\n")
}


##############  Read in the input files

all.data = read.csv(input.file.string)
all.data$plate.strain = paste0(all.data$plate, "_", all.data$strain)

############## Subset to the plates that we want to include

plate.metadata = read.csv(plate.metadata.file.string)
include.plates = (plate.metadata %>% filter(include==T))$plate

all.data = all.data %>% filter(plate %in% include.plates)
all.data$plate = factor(all.data$plate)


############## Subset to the vectors that we want to include

cat("Input plates (before filtering):", length(unique(all.data$plate)), "\n")
cat("Analyzed strains (before filtering):", length(unique(all.data$strain)), "\n")

if (length(included.vectors)>0) {
   strain.metadata = read.csv(strain.metadata.file.string)
   strain.metadata.merge = strain.metadata %>% select(strain, vector, accession)
   all.data = all.data %>% left_join(strain.metadata.merge, by="strain")
   all.data = all.data %>% filter(vector %in% included.vectors)
   
   not.control.data = all.data %>% filter(!(strain %in% control.strains))
   num.not.control.per.plate = not.control.data %>% group_by(plate,strain) %>% summarize(n=n()) %>% group_by(plate) %>% summarize(n=n())
   
   #Remove empty plates - could remove ones with fewer than some number of strains
   all.data = all.data %>% filter(plate %in% unique(num.not.control.per.plate$plate))
   include.plates = unique(all.data$plate)
   all.data$plate = factor(all.data$plate)
}
cat("Analyzed plates (after filtering):", length(unique(all.data$plate)), "\n")
cat("Analyzed strains (after filtering):", length(unique(all.data$strain)), "\n")

##############  Make a general QC graph that highlights the controls
control.data=all.data %>% filter(strain %in% control.strains)
not.control.data = all.data %>% filter(!(strain %in% control.strains))

# how many are left on each plate that are not controls?
num.not.control.per.plate = not.control.data %>% group_by(plate,strain) %>% summarize(n=n()) %>% group_by(plate) %>% summarize(n=n())

#filter out any that don't appear in num.not.control.per.plate

p = ggplot(not.control.data , aes(x=plate, y=growth.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=control.data, width=0.2, size=1, aes(x=plate, y=growth.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0,1.6)

ggsave(paste0(output.base.name,".growth-rate-unnormalized.pdf"), p)

p = ggplot(not.control.data , aes(x=plate, y=GFP.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=control.data, width=0.2, size=1, aes(x=plate, y=GFP.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0,50000)

ggsave(paste0(output.base.name,".GFP-rate-unnormalized.pdf"), p)


#Show control strains only
#ggplot(control.data, aes(x=plate, y=growth.rate, color=strain)) + geom_point()


no.burden.quantile = not.control.data %>% group_by(plate, strain) %>% summarize(growth.rate.mean=mean(growth.rate), GFP.rate.mean=mean(GFP.rate)) %>% group_by(plate) %>% summarize(growth.rate.quantile=quantile(growth.rate.mean, probs=0.8), GFP.rate.quantile=quantile(GFP.rate.mean, probs=0.8, na.rm=T))

##############  Make a  QC graph that connects the controls

control.data.means = control.data %>% group_by(plate, strain) %>% summarize(growth.rate.mean=mean(growth.rate), growth.rate.sd = sd(growth.rate), GFP.rate.mean=mean(GFP.rate), GFP.rate.sd = sd(GFP.rate))

p = ggplot(control.data.means, aes(x=plate, y=growth.rate.mean, color=strain)) + 
   geom_jitter(data=control.data, width=0.2, size=1, aes(x=plate, y=growth.rate, color=strain)) +
   geom_line(data=control.data.means, aes(x=plate, y=growth.rate.mean, color=strain, group=strain)) +
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   #geom_errorbar(aes(ymin=growth.rate.mean-growth.rate.sd, ymax=growth.rate.mean+growth.rate.sd), width=.2,) +
   geom_point(data=no.burden.quantile, aes(x=plate, y=growth.rate.quantile, group="new"), color="black")

ggsave(paste0(output.base.name,".growth-rate-unnormalized-control-mean-and-q80.pdf"), p)

p = ggplot(control.data.means, aes(x=plate, y=GFP.rate.mean, color=strain)) + 
   geom_jitter(data=control.data, width=0.2, size=1, aes(x=plate, y=GFP.rate, color=strain)) +
   geom_line(data=control.data.means, aes(x=plate, y=GFP.rate.mean, color=strain, group=strain)) +
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
#   geom_errorbar(aes(ymin=GFP.rate.mean-GFP.rate.sd, ymax=GFP.rate.mean+GFP.rate.sd), width=0.2) +
   geom_point(data=no.burden.quantile, aes(x=plate, y=GFP.rate.quantile, group="new"), color="black")

ggsave(paste0(output.base.name,".GFP-rate-unnormalized-control-mean-and-q80.pdf"), p)



##############  Determine the no-burden growth rate for each run 
##############  by looking for the maximum density of points

plate.metadata = plate.metadata %>% filter(plate %in% include.plates)
plate.metadata$plate = factor(plate.metadata$plate)

plate.metadata$no.burden.growth.rate = c()
plate.metadata$no.burden.GFP.rate = c()

normalize.stats = data.frame(
   plate=plate.metadata$plate, 
   growth.rate.no.burden=NA, 
   growth.rate.bandwidth=NA,
   GFP.rate.no.burden=NA,
   GFP.rate.bandwidth=NA
)

lower.peak.density.factor = 0.5
for (i in 1:nrow(plate.metadata)) {
   
   #automatically calculated now
   #growth.rate.bw=0.015
   #GFP.rate.bw=300
   
   this.plate = as.character(plate.metadata$plate[i])
   cat(this.plate, "\n")
   plate.no.control.data = not.control.data %>% filter(plate==this.plate)
   
   
   ############### Growth Rate
   
   # Find the peak of maximum no-burden growth
   if (is.na(growth.rate.bw)) {
      this.growth.rate.bw = bw.SJ(plate.no.control.data$growth.rate)
   } else {
      this.growth.rate.bw = growth.rate.bw
   }
   
   this.density = density(plate.no.control.data$growth.rate, bw=this.growth.rate.bw, kernal="gaussian")
   highest.growth.rate.peak.index = which.max(this.density$y)
   highest.growth.rate.peak.density = this.density$y[highest.growth.rate.peak.index]
   highest.growth.rate.peak = this.density$x[highest.growth.rate.peak.index]
   new.highest.growth.rate.peak = highest.growth.rate.peak
   
   for (j in 2:(length(this.density$y)-1)) {
      if ( (this.density$y[j] > this.density$y[j-1]) && (this.density$y[j] > this.density$y[j+1]) ) {
         cat("Peak at growth rate of ", this.density$x[j], " with height of ", this.density$y[j], "\n")
         
         if ( (j >= highest.growth.rate.peak.index) && (this.density$y[j] > highest.growth.rate.peak.density*lower.peak.density.factor) ) {
            cat("  using this peak\n")
            new.highest.growth.rate.peak=this.density$x[j]
         }
      }
   }
   
   no.burden.growth.rate = new.highest.growth.rate.peak
   normalize.stats$growth.rate.no.burden[i] = no.burden.growth.rate
   normalize.stats$growth.rate.bandwidth[i] = this.growth.rate.bw

   p = ggplot(plate.no.control.data, aes(x=growth.rate)) + 
   geom_density(bw=this.growth.rate.bw) + 
      scale_x_continuous(breaks = seq(0, 2, by = 0.1), limits=c(0,2)) + geom_vline(xintercept=no.burden.growth.rate) 
   ggsave(paste0(output.base.name,".",this.plate,".growth-rate-density-plot.pdf"), p)
   
   plate.metadata$no.burden.growth.rate[i] = no.burden.growth.rate
   
   ############### GFP
   
   #Remove some that have no GFP measurements
   plate.no.control.data.has.GFP = plate.no.control.data %>% filter(!is.na(GFP.rate))
   
   if (is.na(GFP.rate.bw)) {
      this.GFP.rate.bw = bw.SJ(plate.no.control.data.has.GFP$GFP.rate)
   } else {
      this.GFP.rate.bw = GFP.rate.bw
   }

   # Find the peak of maximum no-burden GFP
   this.density = density(plate.no.control.data.has.GFP$GFP.rate, bw=this.GFP.rate.bw)
   highest.GFP.rate.peak.index = which.max(this.density$y)
   highest.GFP.rate.peak.density = this.density$y[highest.GFP.rate.peak.index]
   highest.GFP.rate.peak = this.density$x[highest.GFP.rate.peak.index]
   new.highest.GFP.rate.peak = highest.GFP.rate.peak
   
   for (j in 2:(length(this.density$y)-1)) {
      if ( (this.density$y[j] > this.density$y[j-1]) && (this.density$y[j] > this.density$y[j+1]) ) {
         cat("Peak at GFP rate of ", this.density$x[j], " with height of ", this.density$y[j], "\n")
         
         if ( (j >= highest.GFP.rate.peak.index) && (this.density$y[j] > highest.GFP.rate.peak.density*lower.peak.density.factor) ) {
            cat("  using this peak\n")
            new.highest.GFP.rate.peak=this.density$x[j]
         }
      }
   }
   
   no.burden.GFP.rate = new.highest.GFP.rate.peak
   normalize.stats$GFP.rate.no.burden[i] = no.burden.GFP.rate
   normalize.stats$GFP.rate.bandwidth[i] = this.GFP.rate.bw
   
   p = ggplot(plate.no.control.data.has.GFP, aes(x=GFP.rate)) + 
      geom_density(bw=this.GFP.rate.bw) + 
      scale_x_continuous(breaks = seq(0,50000, by = 5000), limits=c(0,50000)) + 
      geom_vline(xintercept=no.burden.GFP.rate) 
   ggsave(paste0(output.base.name,".",this.plate,".GFP-rate-density-plot.pdf"), p)
   
   plate.metadata$no.burden.GFP.rate[i] = no.burden.GFP.rate
}

write.csv(normalize.stats, paste0(output.base.name, ".no.burden.normalize.stats.csv"), row.names=F)


## Normalize to the no.burden.growth.rate
## This sets the normalized point (1,1) to be the same between runs

no.burden.growth.rate.data = data.frame(plate=as.character(plate.metadata$plate), no.burden.growth.rate = plate.metadata$no.burden.growth.rate, no.burden.GFP.rate = plate.metadata$no.burden.GFP.rate)

no.burden.normalized.data = all.data %>% left_join(no.burden.growth.rate.data, by="plate")
no.burden.normalized.data$normalized.growth.rate = no.burden.normalized.data$growth.rate / no.burden.normalized.data$no.burden.growth.rate
no.burden.normalized.data$normalized.GFP.rate = no.burden.normalized.data$GFP.rate / no.burden.normalized.data$no.burden.GFP.rate

no.burden.normalized.control.data = no.burden.normalized.data %>% filter(strain %in% control.strains)
no.burden.normalized.not.control.data = no.burden.normalized.data %>% filter(!(strain %in% control.strains))

p = ggplot(no.burden.normalized.not.control.data , aes(x=plate, y=normalized.growth.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=no.burden.normalized.control.data, width=0.2, size=1, aes(x=plate, y=normalized.growth.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0,1.4)

ggsave(paste0(output.base.name,".growth-rate-no-burden-normalized.pdf"), p)

p = ggplot(no.burden.normalized.not.control.data , aes(x=plate, y=normalized.GFP.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=no.burden.normalized.control.data, width=0.2, size=1, aes(x=plate, y=normalized.GFP.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0,1.4)

ggsave(paste0(output.base.name,".GFP-rate-no-burden-normalized.pdf"), p)

## Plot a regression on the controls for each plate on its own

GFP.versus.growth.rate.normalization.x.intercepts = c()
for (this.plate in unique(all.data$plate)) {
   
   # Line must go through (1,1)
   this.normalized.control.data = no.burden.normalized.data %>% filter(plate==this.plate) 
   this.normalized.control.data = this.normalized.control.data %>% filter(strain %in% control.strains)
   
   to.fit = this.normalized.control.data %>% select(normalized.growth.rate, normalized.GFP.rate)
   
   to.fit$normalized.growth.rate = to.fit$normalized.growth.rate - 1
   to.fit$normalized.GFP.rate = to.fit$normalized.GFP.rate - 1

   the.fit = lm(normalized.GFP.rate~normalized.growth.rate+0, data=to.fit)
   
   #Note, we have to transform coords back to normal here (recalc x-intercept)
   this.fit.x.intercept = 1 - 1/coef(the.fit)[1]
   GFP.versus.growth.rate.normalization.x.intercepts = c(GFP.versus.growth.rate.normalization.x.intercepts, this.fit.x.intercept)
   
   p = ggplot(this.normalized.control.data, aes(x=normalized.growth.rate, y=normalized.GFP.rate, color=strain)) + 
      geom_point() + 
      geom_abline(intercept = 1-coef(the.fit)[1], slope = coef(the.fit)[1], color="red", size=1) + 
      xlim(0,1.2) + 
      ylim(0,1.2)
   
   ggsave(paste0(output.base.name, ".", this.plate, ".no.burden.normalized.control.fit.pdf"), p)
}


# Fit the relation between normalized growth rate and normalized GFP expression

# Using Deming regression to account for error in x and y
this.normalized.control.data = no.burden.normalized.data 
#this.normalized.control.data = this.normalized.control.data %>% filter(strain %in% control.strains)

this.normalized.control.data = 
   this.normalized.control.data %>% 
   group_by(plate,strain) %>% 
   summarize(normalized.growth.rate.mean = mean(normalized.growth.rate), 
             normalized.growth.rate.sd = sd(normalized.growth.rate),
             normalized.GFP.rate.mean = mean(normalized.GFP.rate), 
             normalized.GFP.rate.sd = sd(normalized.GFP.rate)
   )


to.fit = this.normalized.control.data %>% select(plate, strain, normalized.growth.rate.mean, normalized.GFP.rate.mean, normalized.growth.rate.sd, normalized.GFP.rate.sd)

to.fit$normalized.growth.rate.mean = to.fit$normalized.growth.rate.mean - 1
to.fit$normalized.GFP.rate.mean = to.fit$normalized.GFP.rate.mean - 1

all.fit = deming(normalized.GFP.rate.mean~normalized.growth.rate.mean+0, data=to.fit, xstd=normalized.growth.rate.sd, ystd=normalized.GFP.rate.sd)

control.fit = deming(normalized.GFP.rate.mean~normalized.growth.rate.mean+0, data=to.fit %>% filter(strain %in% control.strains), xstd=normalized.growth.rate.sd, ystd=normalized.GFP.rate.sd)

p = ggplot(this.normalized.control.data, aes(x=normalized.growth.rate.mean, y=normalized.GFP.rate.mean)) + 
   geom_point() + 
   geom_point(data=(this.normalized.control.data %>% filter(strain %in% control.strains)), aes(color=strain)) +
   geom_abline(intercept = 1-coef(all.fit)[2], slope = coef(all.fit)[2], color="green", size=1, show.legend=TRUE) + 
   geom_abline(intercept = 1-coef(control.fit)[2], slope = coef(control.fit)[2], color="red", size=1, show.legend=TRUE) #+ 
#   geom_abline(intercept = coef(the.fit.3)[1], slope = coef(the.fit.3)[2], color="blue", size=1) + 
#   xlim(0,1.2) + 
#   ylim(0,1.2)

ggsave(paste0(output.base.name, ".all.plates.no.burden.normalized.fit.pdf"), p)


#Output all normalized values
write.csv(no.burden.normalized.data, paste0(output.base.name, ".no.burden.normalized.all.wells.csv"), row.names=F)

#Further normalize the controls between plates to be consistent with the grand means across plates
use.deming.for.control.fits = TRUE

if (no.control.normalization) {
   final.normalized.data = no.burden.normalized.data
} else {
   
   ## determine the grand means for the controls across all plates
   control.means = no.burden.normalized.control.data %>% filter(!(plate %in% control.fitting.excluded.plates)) %>% group_by(strain) %>% summarize(normalized.growth.rate.grand.mean=mean(normalized.growth.rate), normalized.growth.rate.grand.sd=sd(normalized.growth.rate), normalized.GFP.rate.grand.mean=mean(normalized.GFP.rate), normalized.GFP.rate.grand.sd=sd(normalized.GFP.rate))
   
   print(control.means)
   
   adjustments = data.frame()
   for (this.plate in unique(all.data$plate)) {
      print(this.plate)
      
      this.normalized.control.data.means = 
         no.burden.normalized.data %>% 
         filter(plate==this.plate) %>% 
         filter(strain %in% control.strains) %>% 
         left_join(control.means, by="strain")
      
      to.fit = this.normalized.control.data.means %>% select(normalized.growth.rate, normalized.growth.rate.grand.mean, normalized.growth.rate.grand.mean, normalized.GFP.rate, normalized.GFP.rate.grand.mean)
      
      if (this.plate %in% control.only.normalization.plates) {
         # alternative normalization that uses only control strains -- does not include no-burden normalization
         # force the line to go through (0,0)
         
         the.growth.rate.fit = lm(normalized.growth.rate~normalized.growth.rate.grand.mean, data=to.fit)
         growth.rate.residuals = c(growth.rate.residuals, residuals(the.growth.rate.fit))
         
         the.GFP.rate.fit = lm(normalized.GFP.rate~normalized.GFP.rate.grand.mean, data=to.fit)
         GFP.rate.residuals = c(GFP.rate.residuals, residuals(the.GFP.rate.fit))
         
         adjustments = bind_rows(
            adjustments, 
            data.frame(
               plate=this.plate, 
               growth.rate.normalization.slope = coef(the.growth.rate.fit)[2], 
               growth.rate.normalization.y.intercept = coef(the.growth.rate.fit)[1], 
               growth.rate.ss.res = sum(residuals(the.growth.rate.fit)^2), 
               growth.rate.num.points = length(residuals(the.growth.rate.fit)),  
               GFP.rate.normalization.slope = coef(the.GFP.rate.fit)[2], 
               GFP.rate.normalization.y.intercept = coef(the.GFP.rate.fit)[1],
               GFP.rate.ss.res = sum(residuals(the.GFP.rate.fit)^2), 
               GFP.rate.num.points = length(residuals(the.GFP.rate.fit)
               )
            )
         )
         
      } else {
         # Normal strategy = line must go through (1,1) due to no-burden normalization
         
         if (use.deming.for.control.fits) {
            
            to.fit = this.normalized.control.data.means = 
               no.burden.normalized.data %>% 
               filter(plate==this.plate) %>% 
               filter(strain %in% control.strains)
            
            to.fit = to.fit %>% group_by(strain) %>% summarize(normalized.growth.rate.mean = mean(normalized.growth.rate), normalized.growth.rate.sd = sd(normalized.growth.rate), normalized.GFP.rate.mean = mean(normalized.growth.rate), normalized.GFP.rate.sd = sd(normalized.GFP.rate)) %>% left_join(control.means, by="strain")
            
            to.fit$normalized.growth.rate.mean = to.fit$normalized.growth.rate.mean - 1
            to.fit$normalized.growth.rate.grand.mean = to.fit$normalized.growth.rate.grand.mean - 1
            
            to.fit$normalized.GFP.rate.mean = to.fit$normalized.GFP.rate.mean - 1
            to.fit$normalized.GFP.rate.grand.mean = to.fit$normalized.GFP.rate.grand.mean - 1
            
            the.growth.rate.fit = deming(normalized.growth.rate.mean ~ normalized.growth.rate.grand.mean + 0, data=to.fit, ystd=to.fit$normalized.growth.rate.sd, xstd=to.fit$normalized.growth.rate.grand.sd)
            
            the.GFP.rate.fit = deming(normalized.GFP.rate.mean ~ normalized.GFP.rate.grand.mean + 0, data=to.fit, ystd=to.fit$normalized.GFP.rate.sd, xstd=to.fit$normalized.GFP.rate.grand.sd)
            
            p = ggplot(to.fit, aes(x=normalized.growth.rate.grand.mean+1, y=normalized.growth.rate.mean+1)) + 
               geom_point() + 
               geom_abline(intercept = 1-coef(the.growth.rate.fit)[2], slope = coef(the.growth.rate.fit)[2], color="red", size=1, show.legend=TRUE) + 
               geom_abline(intercept = 0, slope = 1, color="blue", size=1) + 
               geom_errorbar(aes(ymin=normalized.growth.rate.mean+1-normalized.growth.rate.sd, ymax=normalized.growth.rate.mean+1+normalized.growth.rate.sd), width=0) + geom_errorbar(aes(xmin=normalized.growth.rate.grand.mean+1-normalized.growth.rate.grand.sd, xmax=normalized.growth.rate.grand.mean+1+normalized.growth.rate.grand.sd), width=0) +
               xlim(0,1.2) + 
               ylim(0,1.2)
            
            ggsave(paste0(output.base.name, ".", this.plate, ".no.burden.normalized.controls.growth.rate.to.grand.means.fit.pdf"), p)
            
            p = ggplot(to.fit, aes(x=normalized.GFP.rate.grand.mean+1, y=normalized.GFP.rate.mean+1)) + 
               geom_point() + 
               geom_abline(intercept = 1-coef(the.GFP.rate.fit)[2], slope = coef(the.GFP.rate.fit)[2], color="red", size=1, show.legend=TRUE) + 
               geom_abline(intercept = 0, slope = 1, color="blue", size=1) + 
               geom_errorbar(aes(ymin=normalized.GFP.rate.mean+1-normalized.GFP.rate.sd, ymax=normalized.GFP.rate.mean+1+normalized.GFP.rate.sd), width=0) +
               geom_errorbar(aes(xmin=normalized.GFP.rate.grand.mean+1-normalized.GFP.rate.grand.sd, xmax=normalized.GFP.rate.grand.mean+1+normalized.GFP.rate.grand.sd), width=0) +
               
               xlim(0,1.2) + 
               ylim(0,1.2)
            
            ggsave(paste0(output.base.name, ".", this.plate, ".no.burden.normalized.controls.GFP.rate.to.grand.means.fit.pdf"), p)
            
            #Note, we have to transform coords back to normal here (recalc y-intercept)
            adjustments = bind_rows(
               adjustments, 
               data.frame(
                  plate=this.plate, 
                  growth.rate.normalization.slope = as.numeric(coef(the.growth.rate.fit)[2]), 
                  growth.rate.normalization.y.intercept=1-as.numeric(coef(the.growth.rate.fit)[2]), 
                  growth.rate.ss.res = sum(residuals(the.growth.rate.fit)^2), 
                  growth.rate.num.points = length(residuals(the.growth.rate.fit)), 
                  GFP.rate.normalization.slope = as.numeric(coef(the.GFP.rate.fit)[2]), 
                  GFP.rate.normalization.y.intercept=1-as.numeric(coef(the.GFP.rate.fit)[2]),
                  GFP.rate.ss.res = sum(residuals(the.GFP.rate.fit)^2), 
                  GFP.rate.num.points = length(residuals(the.GFP.rate.fit)
                  )
               )
            )
            
            
         } else {
            to.fit$normalized.growth.rate = to.fit$normalized.growth.rate - 1
            to.fit$normalized.growth.rate.grand.mean = to.fit$normalized.growth.rate.grand.mean - 1
            
            to.fit$normalized.GFP.rate = to.fit$normalized.GFP.rate - 1
            to.fit$normalized.GFP.rate.grand.mean = to.fit$normalized.GFP.rate.grand.mean - 1
            
            the.growth.rate.fit = lm(normalized.growth.rate~normalized.growth.rate.grand.mean+0, data=to.fit)
            the.GFP.rate.fit = lm(normalized.GFP.rate~normalized.GFP.rate.grand.mean+0, data=to.fit)
            
            p = ggplot(to.fit, aes(x=normalized.growth.rate.grand.mean+1, y=normalized.growth.rate+1)) + 
               geom_point() + 
               geom_abline(intercept = 1-coef(the.growth.rate.fit)[1], slope = coef(the.growth.rate.fit)[1], color="red", size=1, show.legend=TRUE) + 
               geom_abline(intercept = 0, slope = 1, color="blue", size=1) + 
               xlim(0,1.2) + 
               ylim(0,1.2)
            
            ggsave(paste0(output.base.name, ".", this.plate, ".no.burden.normalized.controls.growth.rate.to.grand.means.fit.pdf"), p)
            
            p = ggplot(to.fit, aes(x=normalized.GFP.rate.grand.mean+1, y=normalized.GFP.rate+1)) + 
               geom_point() + 
               geom_abline(intercept = 1-coef(the.GFP.rate.fit)[1], slope = coef(the.GFP.rate.fit)[1], color="red", size=1, show.legend=TRUE) + 
               geom_abline(intercept = 0, slope = 1, color="blue", size=1) + 
               xlim(0,1.2) + 
               ylim(0,1.2)
            
            ggsave(paste0(output.base.name, ".", this.plate, ".no.burden.normalized.controls.GFP.rate.to.grand.means.fit.pdf"), p)
            
            #Note, we have to transform coords back to normal here (recalc y-intercept)
            adjustments = bind_rows(
               adjustments, 
               data.frame(
                  plate=this.plate, 
                  growth.rate.normalization.slope = coef(the.growth.rate.fit)[1], 
                  growth.rate.normalization.y.intercept=1-coef(the.growth.rate.fit)[1]), 
                  growth.rate.ss.res = sum(residuals(the.growth.rate.fit)^2), 
                  growth.rate.num.points = length(residuals(the.growth.rate.fit),  
                  GFP.rate.normalization.slope = coef(the.GFP.rate.fit)[1]), 
                  GFP.rate.normalization.y.intercept=1-coef(the.GFP.rate.fit)[1],
                  GFP.rate.ss.res = sum(residuals(the.GFP.rate.fit)^2), 
                  GFP.rate.num.points = length(residuals(the.GFP.rate.fit)
               )
            )
         }
      }
   }
   
   
   adjustments$growth.rate.rmse = sqrt(adjustments$growth.rate.ss.res/adjustments$growth.rate.num.points)
   overall.growth.rate.rmse = sqrt(sum(adjustments$growth.rate.ss.res)/sum(adjustments$growth.rate.num.points))
      
   adjustments$GFP.rate.rmse = sqrt(adjustments$GFP.rate.ss.res/adjustments$GFP.rate.num.points)
   overall.GFP.rate.rmse = sqrt(sum(adjustments$GFP.rate.ss.res)/sum(adjustments$GFP.rate.num.points))
   
   write.csv(adjustments, paste0(output.base.name, ".fits.of.no.burden.normalized.controls.to.grand.means.csv"), row.names=F)
   
   ## Output some stats about how well the fitting went on each plate
   cat("Statistics for fitting control strains on each plate to grand means\n")
   cat("Overall growth rate RMSE:", overall.growth.rate.rmse, "\n")
   cat("Overall GFP    rate RMSE:", overall.GFP.rate.rmse, "\n")
   
   
   final.normalized.data = no.burden.normalized.data
   final.normalized.data = final.normalized.data %>% left_join(adjustments, by="plate")
   
   #Transform points into fit control coordinates x = (y-b)/m
   final.normalized.data$normalized.growth.rate = (final.normalized.data$normalized.growth.rate - final.normalized.data$growth.rate.normalization.y.intercept) / final.normalized.data$growth.rate.normalization.slope 
   
   final.normalized.data$normalized.GFP.rate = (final.normalized.data$normalized.GFP.rate - final.normalized.data$GFP.rate.normalization.y.intercept) / final.normalized.data$GFP.rate.normalization.slope
   
}

# Fit and plot the relation between normalized growth rate and normalized GFP expression

# Using Deming regression to account for error in x and x
this.normalized.control.data = final.normalized.data 
#this.normalized.control.data = this.normalized.control.data %>% filter(strain %in% control.strains)

this.normalized.control.data = 
   this.normalized.control.data %>% 
   group_by(plate,strain) %>% 
   summarize(normalized.growth.rate.mean = mean(normalized.growth.rate), 
             normalized.growth.rate.sd = sd(normalized.growth.rate),
             normalized.GFP.rate.mean = mean(normalized.GFP.rate), 
             normalized.GFP.rate.sd = sd(normalized.GFP.rate)
   )


to.fit = this.normalized.control.data %>% select(plate, strain, normalized.growth.rate.mean, normalized.GFP.rate.mean, normalized.growth.rate.sd, normalized.GFP.rate.sd)

to.fit$normalized.growth.rate.mean = to.fit$normalized.growth.rate.mean - 1
to.fit$normalized.GFP.rate.mean = to.fit$normalized.GFP.rate.mean - 1

all.fit = deming(normalized.GFP.rate.mean~normalized.growth.rate.mean+0, data=to.fit, xstd=normalized.growth.rate.sd, ystd=normalized.GFP.rate.sd)

control.fit = deming(normalized.GFP.rate.mean~normalized.growth.rate.mean+0, data=to.fit %>% filter(strain %in% control.strains), xstd=normalized.growth.rate.sd, ystd=normalized.GFP.rate.sd)

p = ggplot(this.normalized.control.data, aes(x=normalized.growth.rate.mean, y=normalized.GFP.rate.mean)) + 
   geom_point() + 
   geom_point(data=(this.normalized.control.data %>% filter(strain %in% control.strains)), aes(color=strain)) +
   geom_abline(intercept = 1-coef(all.fit)[2], slope = coef(all.fit)[2], color="green", size=1, show.legend=TRUE) + 
   geom_abline(intercept = 1-coef(control.fit)[2], slope = coef(control.fit)[2], color="red", size=1, show.legend=TRUE) #+ 
   #   geom_abline(intercept = coef(the.fit.3)[1], slope = coef(the.fit.3)[2], color="blue", size=1) + 
   #xlim(0,1.2) + 
   #ylim(0,1.2)

ggsave(paste0(output.base.name, ".all.plates.no.burden.and.control.normalized.fit.pdf"), p)


#Output all normalized values
write.csv(final.normalized.data, paste0(output.base.name, ".no.burden.and.control.normalized.all.wells.csv"), row.names=F)


final.normalized.control.data=final.normalized.data %>% filter(strain %in% control.strains)
final.normalized.not.control.data = final.normalized.data %>% filter(!(strain %in% control.strains))

p = ggplot(final.normalized.not.control.data , aes(x=plate, y=normalized.growth.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=final.normalized.control.data, width=0.2, size=1, aes(x=plate, y=normalized.growth.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0.4,1.2)

ggsave(paste0(output.base.name,".growth-rate-no-burden-and-control-normalized.pdf"), p)

p = ggplot(final.normalized.not.control.data , aes(x=plate, y=normalized.GFP.rate, color=plate)) + 
   geom_jitter( width=0.2, size=0.3, color="gray") + 
   geom_jitter(data=final.normalized.control.data, width=0.2, size=1, aes(x=plate, y=normalized.GFP.rate, color=strain)) + 
   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
   ylim(0.4,1.2)

ggsave(paste0(output.base.name,".GFP-rate-no-burden-and-control-normalized.pdf"), p)


########################################################################################
### File for performing stats while keeping unique plate-strain combinations

parts = final.normalized.not.control.data
p.values = data.frame()
for (this.plate.strain in unique(parts$plate.strain)) {
   
   this.strain.plate.data = parts %>% filter(plate.strain == this.plate.strain)
   
   #cat(this.plate.strain, "  ", length(this.strain.plate.data$normalized.growth.rate), "\n")
   
   if (length(this.strain.plate.data$normalized.growth.rate) > 1) {
      test.result = t.test(this.strain.plate.data$normalized.growth.rate-1, alternative = "less")
   } else {
      test.result = data.frame(p.value=NA)
   }
   
   p.values = bind_rows(p.values, data.frame(plate.strain=this.plate.strain, growth.rate.reduced.p.value = test.result$p.value ))
}
p.values$growth.rate.reduced.adj.p.value = p.adjust(p.values$growth.rate.reduced.p.value, method="BH")

parts = final.normalized.data

parts.means = parts %>% group_by(plate, strain, plate.strain) %>% summarize(replicates=n(), accession=paste(unique(accession), collapse=","), normalized.growth.rate.mean=mean(normalized.growth.rate), normalized.growth.rate.sd=sd(normalized.growth.rate), normalized.growth.rate.sem = normalized.growth.rate.sd/sqrt(replicates), normalized.growth.rate.95CI.range =  normalized.growth.rate.sem*qt(0.975, df=replicates-1), normalized.growth.rate.cv=sd(normalized.growth.rate)/mean(normalized.growth.rate), normalized.GFP.rate.mean=mean(normalized.GFP.rate), normalized.GFP.rate.sd=sd(normalized.GFP.rate), normalized.GFP.rate.sem = normalized.GFP.rate.sd/sqrt(replicates), normalized.GFP.rate.95CI.range =  normalized.GFP.rate.sem*qt(0.975, df=replicates-1), normalized.GFP.rate.cv=sd(normalized.GFP.rate)/mean(normalized.GFP.rate))
parts.means = parts.means %>%left_join(p.values, by="plate.strain")
#parts.means = parts.means %>%left_join(translational.burden.fraction.p.values, by="plate.strain")
parts.means = parts.means %>% group_by() %>% select(-plate.strain)

parts.means$burden.category = c()
parts.means$burden.category = "no burden";
parts.means$burden.category[parts.means$growth.rate.reduced.adj.p.value < 0.05] = "significant"
parts.means$burden.category[parts.means$strain %in% control.strains] = "control"

parts.means$burden.mean = 1-parts.means$normalized.growth.rate.mean
parts.means$burden.sd = parts.means$normalized.growth.rate.sd
parts.means$burden.sem = parts.means$normalized.growth.rate.sem
parts.means$burden.95CI.range = parts.means$normalized.growth.rate.95CI.range
parts.means$burden.cv = abs(parts.means$burden.sd  / parts.means$burden.mean)

write.csv(parts.means, paste0(output.base.name, ".plate-strain.burden.csv"), row.names=F)

########################################################################################
### File for performing stats that only keeps one entry for each strain
### (That is, it combines data for a strain across different plates)

parts = final.normalized.not.control.data

p.values = data.frame()
for (this.strain in unique(parts$strain)) {
   
   this.strain.data = parts %>% filter(strain == this.strain)
   
   #cat(this.plate.strain, "  ", length(this.strain.plate.data$normalized.growth.rate), "\n")
   
   if (length(this.strain.data$normalized.growth.rate) > 1) {
      
      test.result = t.test(this.strain.data$normalized.growth.rate-1, alternative = "less")
      #cat(this.plate.strain, "  ", test.result$p.value, "\n")

   } else {
      test.result = data.frame(p.value=NA)
   }
   
   p.values = bind_rows(p.values, data.frame(strain=this.strain, growth.rate.reduced.p.value = test.result$p.value ))
}
p.values$growth.rate.reduced.adj.p.value = p.adjust(p.values$growth.rate.reduced.p.value, method="BH")

parts = final.normalized.data

parts.means = parts %>% group_by(strain) %>% summarize(replicates=n(), normalized.growth.rate.mean=mean(normalized.growth.rate), normalized.growth.rate.sd=sd(normalized.growth.rate), normalized.growth.rate.sem = normalized.growth.rate.sd/sqrt(replicates), normalized.growth.rate.95CI.range =  normalized.growth.rate.sem*qt(0.975, df=replicates-1), normalized.growth.rate.cv=sd(normalized.growth.rate)/mean(normalized.growth.rate), normalized.GFP.rate.mean=mean(normalized.GFP.rate), normalized.GFP.rate.sd=sd(normalized.GFP.rate), normalized.GFP.rate.sem = normalized.GFP.rate.sd/sqrt(replicates), normalized.GFP.rate.95CI.range = normalized.GFP.rate.sem*qt(0.975, df=replicates-1), normalized.GFP.rate.cv=sd(normalized.GFP.rate)/mean(normalized.GFP.rate), plates=paste(unique(plate), collapse=","), vector=paste(unique(vector), collapse=","), accession=paste(unique(accession), collapse=","))
parts.means = parts.means %>%left_join(p.values, by="strain")

parts.means = parts.means %>% group_by()

parts.means$burden.category = c()
parts.means$burden.category = "no burden";
parts.means$burden.category[parts.means$growth.rate.reduced.adj.p.value < 0.05] = "significant"
parts.means$burden.category[parts.means$strain %in% control.strains] = "control"

parts.means$burden.mean = 1-parts.means$normalized.growth.rate.mean
parts.means$burden.sd = parts.means$normalized.growth.rate.sd
parts.means$burden.sem = parts.means$normalized.growth.rate.sem
parts.means$burden.95CI.range = parts.means$normalized.growth.rate.95CI.range
parts.means$burden.cv = abs(parts.means$burden.sd  / parts.means$burden.mean)

write.csv(parts.means, paste0(output.base.name, ".strain.burden.csv"), row.names=F)





########################################################################################
### File for performing stats that only keeps one entry for each part
### (That is, it combines data for all strains with a part and across different plates)

parts = final.normalized.not.control.data
control.accessions = (strain.metadata %>% filter(strain %in% control.strains))$accession

p.values = data.frame()
for (this.accession in unique(parts$accession)) {
   
   this.accession.data = parts %>% filter(accession == this.accession)
   
   if (length(this.accession.data$normalized.growth.rate) > 1) {
      
      test.result = t.test(this.accession.data$normalized.growth.rate-1, alternative = "less")

   } else {
      test.result = data.frame(p.value=NA)
   }
   
   p.values = bind_rows(p.values, data.frame(accession=this.accession, growth.rate.reduced.p.value = test.result$p.value ))
}
p.values$growth.rate.reduced.adj.p.value = p.adjust(p.values$growth.rate.reduced.p.value, method="BH")

parts = final.normalized.data

parts.means = parts %>% group_by(accession) %>% summarize(replicates=n(), normalized.growth.rate.mean=mean(normalized.growth.rate), normalized.growth.rate.sd=sd(normalized.growth.rate), normalized.growth.rate.sem = normalized.growth.rate.sd/sqrt(replicates), normalized.growth.rate.95CI.range =  normalized.growth.rate.sem*qt(0.975, df=replicates-1), normalized.growth.rate.cv=sd(normalized.growth.rate)/mean(normalized.growth.rate), normalized.GFP.rate.mean=mean(normalized.GFP.rate), normalized.GFP.rate.sd=sd(normalized.GFP.rate), normalized.GFP.rate.sem = normalized.GFP.rate.sd/sqrt(replicates), normalized.GFP.rate.95CI.range = normalized.GFP.rate.sem*qt(0.975, df=replicates-1), normalized.GFP.rate.cv=sd(normalized.GFP.rate)/mean(normalized.GFP.rate), plates=paste(sort(unique(plate)), collapse=","), strains=paste(sort(unique(strain)), collapse=","), strain=unique(strain)[1], vectors=paste(sort(unique(vector)), collapse=","))

parts.means = parts.means %>%left_join(p.values, by="accession")

parts.means = parts.means %>% group_by()

parts.means$burden.category = c()
parts.means$burden.category = "no burden";
parts.means$burden.category[parts.means$growth.rate.reduced.adj.p.value < 0.05] = "significant"
parts.means$burden.category[parts.means$accession %in% control.accessions] = "control"

parts.means$burden.mean = 1-parts.means$normalized.growth.rate.mean
parts.means$burden.sd = parts.means$normalized.growth.rate.sd
parts.means$burden.sem = parts.means$normalized.growth.rate.sem
parts.means$burden.95CI.range = parts.means$normalized.growth.rate.95CI.range
parts.means$burden.cv = abs(parts.means$burden.sd  / parts.means$burden.mean)

write.csv(parts.means, paste0(output.base.name, ".part.burden.csv"), row.names=F)

