#!/usr/bin/env Rscript

#igem2019 specific analyses

library(tidyverse)
library(ggplot2)
library(cowplot)
library(deming)
library(lmtest)

#debug
input.file.string="04-normalization/output.part.burden.csv"
output.base.name="05-burden-final-output/output"
metadata.file.string = "igem2019_strain_metadata.csv"

if (!exists("input.file.string")) {
   suppressMessages(library(optparse))
   
   option_list = list(
      make_option(
         c("-i", "--input"), type="character", default=NULL, 
         help="Input normalized CSV file generated by burden_normalize.R script.", metavar="normalized.csv"
      ),
      make_option(   
         c("-o", "--output"), type="character", default=NULL, 
         help="Output base name.", metavar="output"
      ),
      make_option(
         c("-m", "--metadata"), type="character", default=NULL, 
         help="CSV file containing one line per strain analyzed.", metavar="strain_metadata.csv"
      )
   )
   
   usage_string = paste(
      "burden_normalize.R -i merged.csv -o output -m metadata.csv\n\n",
      sep = ""
   ) 
   
   opt_parser = OptionParser(usage=usage_string, option_list=option_list)
   opt = parse_args(opt_parser)
   
   if (is.null(opt$input) || is.null(opt$output) || is.null(opt$metadata)) {
      print_help(opt_parser)
      stop("You must supply the -i, -o, -m, and -c arguments", call.=FALSE)
   }
   
   input.file.string = opt$input
   output.base.name = opt$output
   metadata.file.string = opt$metadata
}


cat("Input file of normalized values:  ", input.file.string, "\n")
cat("Input file of strain metadata: ", metadata.file.string, "\n")
cat("Output base name: ", output.base.name, "\n")

##############  Read in the input files

all.data = read.csv(input.file.string)
all.data$plate.strain = paste0(all.data$plate, "_", all.data$strain)

strain.metadata = read.csv(metadata.file.string)


################################################################################
## Read in the input files and subset to the data we want to include

#Only trust if we have at least two good measurements (not applicable to control strains)
all.data = all.data %>% filter( (replicates>=2) | (burden.category == "control"))
#all.data = all.data %>% filter(burden.cv<2)

################################################################################
### How many unique strains did we analyze total?

noncontrolstrains = all.data %>% filter(burden.category != "control")
cat("Total strains analyzed:", length(unique(noncontrolstrains$strain)), "\n")

################################################################################
### Plot testing for trend in normalized standard error of the man versus growth rate

if (T) {
   
   non.control.parts.means = all.data %>% filter(burden.category != "control")
   
   p = ggplot(non.control.parts.means, aes(x=normalized.growth.rate.mean, y=normalized.growth.rate.sem)) + geom_point(alpha=0.5,fill="black", stroke=NA, size=3) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + geom_smooth(data=non.control.parts.means, aes(x=normalized.growth.rate.mean, y=normalized.growth.rate.sem), method = "lm", se = FALSE, inherit.aes=F) + theme_cowplot(12) + panel_border(color = "black")
   p
   ggsave(paste0(output.base.name, ".normalized.sem.versus.growth.rate.pdf"), plot=p, width=8, height=5)
   
   
   fit1 = lm(normalized.growth.rate.sem~normalized.growth.rate.mean, data=non.control.parts.means)
   
  #used for t-test
  print(summary(fit1))   
   
   fit2 = lm(normalized.growth.rate.sem~1, data=non.control.parts.means)
   
   lrtest(fit2, fit1)
   
   cat("Is there a trend in the coefficient of variation such that smaller values have a higher SEM?\n")
   
   print(anova(fit2, fit1))
   
}

################################################################################
# Distribution plots showing where the controls end up

control.means = all.data %>% filter(burden.category=="control") %>% group_by(strain) %>% summarize(normalized.growth.rate.grand.mean=mean(normalized.growth.rate.mean), normalized.GFP.rate.grand.mean=mean(normalized.GFP.rate.mean))

control.burdens = control.means
control.burdens$burden.mean = 1 - control.burdens$normalized.growth.rate.grand.mean
control.burdens = control.burdens %>% select(-normalized.growth.rate.grand.mean, -normalized.GFP.rate.grand.mean)
control.burdens = rbind(data.frame(strain="no burden", burden.mean=0), control.burdens)

p = ggplot(all.data %>% filter(burden.category!="control"), aes(x=burden.mean)) +
   geom_density(bw=0.005) + 
   scale_x_continuous(limits = c(-0.1,0.6), breaks = seq(-0.1,0.6, by=0.1), expand = c(0, 0)) +
   #scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
   geom_vline(data = control.burdens, aes(xintercept=burden.mean, color=strain)) +
   theme_cowplot(12) +
   panel_border(color = "black")

ggsave(paste0(output.base.name, ".burden-normalized-distribution.pdf"), plot=p, width=8, height=5)

p = ggplot(all.data %>% filter(burden.category!="control"), aes(x=normalized.growth.rate.mean)) +
   geom_density(bw=0.005) + 
   scale_x_continuous(limits = c(0.4,1.3), breaks = seq(0.4,1.3, by=0.1), expand = expansion(add = c(0.02, 0.02))) +
   #scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
   geom_vline(data = control.burdens, aes(xintercept=1-burden.mean, color=strain)) +
   theme_cowplot(12) +
   panel_border(color = "black")

ggsave(paste0(output.base.name, ".growth-rate-normalized-distribution.pdf"), plot=p, width=8, height=5)

control.burdens = control.means
control.burdens$GFP.rate.mean = control.burdens$normalized.GFP.rate.grand.mean
control.burdens = control.burdens %>% select(-normalized.growth.rate.grand.mean, -normalized.GFP.rate.grand.mean)
control.burdens = rbind(data.frame(strain="no burden", GFP.rate.mean=1), control.burdens)

p = ggplot(all.data %>% filter(burden.category!="control"), aes(x=1-normalized.GFP.rate.mean)) + 
   geom_density(bw=0.005) + 
   xlim(-0.4, 0.6) + 
   geom_vline(data = control.burdens, aes(xintercept=1-GFP.rate.mean, color=strain)) +
   theme_cowplot(12) +
   panel_border(color = "black")

ggsave(paste0(output.base.name, ".GFP-rate-reduction-normalized-distribution.pdf"), plot=p, width=8, height=5)


p = ggplot(all.data %>% filter(burden.category!="control"), aes(x=normalized.GFP.rate.mean)) + 
   geom_density(bw=0.005) + 
   scale_x_continuous(limits = c(0.4,1.3), breaks = seq(0.4,1.3, by=0.1), expand = expansion(add = c(0.02, 0.02))) +
   geom_vline(data = control.burdens, aes(xintercept=GFP.rate.mean, color=strain)) +
   theme_cowplot(12) +
   panel_border(color = "black")

ggsave(paste0(output.base.name, ".GFP-rate-normalized-distribution.pdf"), plot=p, width=8, height=5)

##############  Make a general graph showing all of the points
control.data=all.data %>% filter(burden.category=="control")
not.control.data = all.data %>% filter(!(burden.category=="control"))

min.plot.coord = 0.4
max.plot.coord = 1.3

# What is the fit slope for the controls?
control.data$sub.normalized.GFP.rate.mean = control.data$normalized.GFP.rate.mean - 1
control.data$sub.normalized.growth.rate.mean = control.data$normalized.growth.rate.mean - 1

the.fit = deming(sub.normalized.GFP.rate.mean ~ sub.normalized.growth.rate.mean + 0, data=control.data, xstd=normalized.growth.rate.sd, ystd=normalized.GFP.rate.sd)
the.slope = coef(the.fit)[2]
the.intercept = 1-the.slope

#sub.slope = coef(fit4)[2]
#sub.intercept = -sub.slope+1+coef(fit4)[1]

ggplot(all.data , aes(x=normalized.growth.rate.mean, y=normalized.GFP.rate.mean, color=burden.category)) + 
   geom_point() + coord_cartesian(xlim = c(min.plot.coord, max.plot.coord ), ylim = c(min.plot.coord, max.plot.coord)) + geom_abline(intercept = the.intercept, slope = the.slope) +
   geom_errorbarh(aes(xmin=normalized.growth.rate.mean-normalized.growth.rate.sd, xmax=normalized.growth.rate.mean+normalized.growth.rate.sd, height=0.01)) +
   geom_errorbar(aes(ymin=normalized.GFP.rate.mean-normalized.GFP.rate.sd, ymax=normalized.GFP.rate.mean+normalized.GFP.rate.sd, width=0.01))


ggplot(all.data , aes(x=normalized.growth.rate.mean, y=normalized.GFP.rate.mean, color=burden.category)) + 
   geom_point() + coord_cartesian(xlim = c(min.plot.coord, max.plot.coord ), ylim = c(min.plot.coord, max.plot.coord)) + geom_abline(intercept = 0, slope = 1, show.legend=T) + geom_abline(intercept = the.intercept, slope = the.slope, color="blue") + geom_hline(aes(yintercept=1)) + geom_vline(aes(xintercept=1))



##### Analyze the replicate runs
plot_with_error_bars <- function(in.data) {
   
   ggplot(in.data , aes(x=normalized.growth.rate.mean, y=normalized.GFP.rate.mean, color=strain, shape=plate)) + 
      geom_point(size=2) + 
      coord_cartesian(xlim = c(min.plot.coord, max.plot.coord ), ylim = c(min.plot.coord, max.plot.coord)) + 
      geom_abline(intercept = 0, slope = 1) + geom_abline(intercept = sub.intercept, slope = sub.slope, color="blue") +
      geom_errorbarh(aes(xmin=normalized.growth.rate.mean-normalized.growth.rate.sd, xmax=normalized.growth.rate.mean+normalized.growth.rate.sd, height=0.01)) +
      geom_errorbar(aes(ymin=normalized.GFP.rate.mean-normalized.GFP.rate.sd, ymax=normalized.GFP.rate.mean+normalized.GFP.rate.sd, width=0.01))
}

################################################################################
### Reproducibility tests
#in.data=all.data %>% filter (plate %in% c("exp003", "exp005"))
#plot_with_error_bars(in.data)

#exp54 is not included currently, but this should be a duplicate of the test strains
#in.data=all.data %>% filter (experiment %in% c("exp050", "exp054"))

#RFP Strains
#in.data=all.data %>% filter (plate %in% c("exp045")) %>% filter (!burden.category %in% c("control"))
#plot_with_error_bars(in.data)

################################################################################
### Two dimensional test of being above the line and confidence intervals on this


t.above.line <- function(x.mean,x.sd,y.mean,y.sd,this.n,slope,intercept) {
   
   ## this library clashes with dplyr
   library(Hmisc)
   
   cat(x.mean,x.sd,y.mean,y.sd,this.n,slope,intercept,"\n")
   
   chunk.size=0.002
   chunk.offset.to.middle = chunk.size/2
   tdata = expand.grid(x=seq(from=chunk.offset.to.middle, to=2-chunk.offset.to.middle, by=chunk.size), y=seq(from=chunk.offset.to.middle,to=2-chunk.offset.to.middle,by=chunk.size))
   
   tdata$d = dt( (tdata$x-x.mean)/(x.sd/sqrt(this.n)) ,df=this.n-1) *  dt( (tdata$y-y.mean)/(y.sd/sqrt(this.n)) ,df=this.n-1)
   
   tdata$d =  tdata$d / sum(tdata$d)
   
   ggplot(tdata, aes(x,y)) + geom_raster(aes(fill = d))
   tdata$f = (tdata$y-(intercept + tdata$x * slope)) / (1 - (intercept + tdata$x * slope))
   
   q = wtd.quantile(tdata$f, weights=tdata$d, normwt=T, probs=c(0.025, 0.500, 0.975))
   
   ##return two-tailed test
   greater.p.value = sum((tdata %>% filter(tdata$f<0))$d) + sum((tdata %>% filter(tdata$f==0))$d)/2
   
   two.tailed.p.value = greater.p.value
   if (two.tailed.p.value > 0.5) {
      two.tailed.p.value = 1 - two.tailed.p.value
   }
   two.tailed.p.value=2*two.tailed.p.value
   
   return(
      data.frame(
         two.tailed.p.value = two.tailed.p.value,
         greater.p.value = greater.p.value,
         L95 = q[[1]],
         median = q[[2]],
         U95 = q[[3]]
      )
   )
   
   detach("package:Hmisc", unload=TRUE)
}

all.data$other.burden.greater.p.value = NA
all.data$other.burden.two.tailed.p.value = NA
all.data$other.burden.maximum.likelihood = NA
all.data$other.burden.median = NA
all.data$other.burden.fraction.L95 = NA
all.data$other.burden.fraction.U95 = NA

if (T) {
   for(i in 1:nrow(all.data)) {
      cat("\nCalculating:", i,"\n")
      this.strain.experiment=all.data[i,]
      if (is.na(this.strain.experiment$normalized.GFP.rate.mean)) {
         next
      }
      ret_val=t.above.line(
         this.strain.experiment$normalized.growth.rate.mean,
         this.strain.experiment$normalized.growth.rate.sd,
         this.strain.experiment$normalized.GFP.rate.mean,
         this.strain.experiment$normalized.GFP.rate.sd,
         this.strain.experiment$replicates,
         the.slope,
         the.intercept
      )
      print(ret_val)
      
      all.data$other.burden.greater.p.value[i] = ret_val$greater.p.value 
      all.data$other.burden.two.tailed.p.value[i] = ret_val$two.tailed.p.value 
      
      all.data$other.burden.maximum.likelihood[i] = (all.data$normalized.GFP.rate.mean[i]-(0 + all.data$normalized.growth.rate.mean[i] * 1)) / (1 - (0 + all.data$normalized.growth.rate.mean[i] * 1))
      
      all.data$other.burden.median[i] = ret_val$median
      all.data$other.burden.fraction.L95[i] = ret_val$L95 
      all.data$other.burden.fraction.U95[i] = ret_val$U95 
      
   }
}

#drop controls
all.data$other.burden.greater.adj.p.value = all.data$other.burden.greater.p.value
all.data$other.burden.greater.adj.p.value[all.data$burden.category!="significant"] = NA
all.data$other.burden.greater.adj.p.value[all.data$burden.mean<0.1] = NA
all.data$other.burden.greater.adj.p.value[!is.na(all.data$other.burden.greater.adj.p.value)] = p.adjust(all.data$other.burden.greater.adj.p.value[!is.na(all.data$other.burden.greater.adj.p.value)], method="BH")

all.data$other.burden.two.tailed.adj.p.value = all.data$other.burden.two.tailed.p.value
all.data$other.burden.two.tailed.adj.p.value[all.data$burden.category!="significant"] = NA
all.data$other.burden.two.tailed.adj.p.value[all.data$burden.mean<0.1] = NA
all.data$other.burden.two.tailed.adj.p.value[!is.na(all.data$other.burden.two.tailed.adj.p.value)] = p.adjust(all.data$other.burden.two.tailed.adj.p.value[!is.na(all.data$other.burden.two.tailed.adj.p.value)], method="BH")

#### Graph coloring these by which are significant
all.data$other.burden.greater.significant = "not tested"
all.data$other.burden.greater.significant[!is.na(all.data$other.burden.greater.adj.p.value)] = "not significant"
all.data$other.burden.greater.significant[all.data$other.burden.greater.adj.p.value <= 0.05] = "significant"
all.data$other.burden.greater.significant = factor(all.data$other.burden.greater.significant, levels=c("not tested", "not significant", "significant"))

all.data$other.burden.two.tailed.significant = "not tested"
all.data$other.burden.two.tailed.significant[!is.na(all.data$other.burden.greater.adj.p.value)] = "not significant"
all.data$other.burden.two.tailed.significant[all.data$other.burden.two.tailed.adj.p.value <= 0.05] = "significant"
all.data$other.burden.two.tailed.significant = factor(all.data$other.burden.two.tailed.significant, levels=c("not tested", "not significant", "significant"))



all.data$burden.category=factor(all.data$burden.category, levels=c("no burden", "control", "significant"))

all.data = all.data %>% arrange(burden.category, other.burden.greater.significant)

### Let's put back all of the metadata
print.data = all.data %>% left_join(strain.metadata %>% select(-accession), by="strain")


write.csv(print.data, paste0(output.base.name, ".burden_confidence.csv"), row.names=F)
print.data = read.csv(paste0(output.base.name, ".burden_confidence.csv"))

print.data$other.burden.greater.significant = factor(print.data$other.burden.greater.significant, levels=c("not tested", "not significant", "significant"))
print.data$other.burden.two.tailed.significant = factor(print.data$other.burden.two.tailed.significant, levels=c("not tested", "not significant", "significant"))

library(ggrepel)

p = ggplot(
   print.data, 
   aes(
      x=normalized.growth.rate.mean, 
      y=normalized.GFP.rate.mean, 
      color=burden.category, 
      shape=other.burden.greater.significant, 
      #shape=other.burden.two.tailed.significant, 
      label=plate.strain,
   )
) +
   scale_colour_manual(values=c("#4147F7", "#000000", "#FF6EFC")) +
   scale_alpha_manual(values=c(1, 0.3, 1)) +
   #scale_colour_manual(values=c("#009E73", "#56B4E9", "#000000")) + 
   coord_cartesian(
      xlim = c(min.plot.coord, max.plot.coord), 
      ylim = c(min.plot.coord, max.plot.coord)
   ) + 
   scale_x_continuous(breaks = seq(0,15, by=0.1)) +
   scale_y_continuous(breaks = seq(0,15, by=0.1))+
   geom_abline(intercept = the.intercept, slope = the.slope, show.legend=T, linetype = "dashed") + 
   geom_hline(aes(yintercept=1), color="grey") + 
   geom_vline(aes(xintercept=1), color="grey") +
   geom_errorbarh(
      aes(
         xmin=normalized.growth.rate.mean-normalized.growth.rate.95CI.range, 
         xmax=normalized.growth.rate.mean+normalized.growth.rate.95CI.range, 
         height=0.01,
      ),
      alpha=0.2
   ) +
   geom_errorbar(
      aes(
         ymin=normalized.GFP.rate.mean-normalized.GFP.rate.95CI.range, 
         ymax=normalized.GFP.rate.mean+normalized.GFP.rate.95CI.range, 
         width=0.01
      ),
      alpha=0.2
   ) + 
   geom_point(aes(alpha=burden.category), size=2) + 
   geom_text_repel(
      #data = subset(print.data, burden.category=="significant"), 
      data = subset(print.data, other.burden.greater.significant=="significant"), 
      #data = subset(print.data, other.burden.two.tailed.significant=="significant"), 
      
      segment.size = 0.2, 
      size = 2.5, 
      box.padding = 0.5,
      force = 20, 
      point.padding = 0.3, 
      color="black"
   ) +
   theme_cowplot(12) +
   panel_border(color = "black") + 
   NULL

p
ggsave(paste0(output.base.name, ".burden_significantly_greater_labeled.pdf"), plot=p, width=10, height=7)

p = ggplot(
   print.data, 
   aes(
      x=normalized.growth.rate.mean, 
      y=normalized.GFP.rate.mean, 
      color=burden.category, 
      shape=other.burden.greater.significant, 
      label=accession,
   )
) +
   scale_colour_manual(values=c("#4147F7", "#000000", "#FF6EFC")) +
   scale_alpha_manual(values=c(1, 0.3, 1)) +
   #scale_colour_manual(values=c("#009E73", "#56B4E9", "#000000")) + 
   coord_cartesian(
      xlim = c(min.plot.coord, max.plot.coord), 
      ylim = c(min.plot.coord, max.plot.coord)
   ) + 
   scale_x_continuous(breaks = seq(0,15, by=0.1)) +
   scale_y_continuous(breaks = seq(0,15, by=0.1))+
   geom_abline(intercept = the.intercept, slope = the.slope, show.legend=T, linetype = "dashed") + 
   geom_hline(aes(yintercept=1), color="grey") + 
   geom_vline(aes(xintercept=1), color="grey") + 
   geom_point(aes(alpha=burden.category), size=2) + 
   geom_text_repel(
      #data = subset(all.data, burden.category=="significant"), 
      data = subset(print.data, other.burden.greater.significant=="significant"), 
      
      segment.size = 0.2, 
      size = 2.5, 
      box.padding = 0.5,
      force = 20, 
      point.padding = 0.3, 
      color="black"
   ) +
   theme_cowplot(12) +
   panel_border(color = "black")

p
ggsave(paste0(output.base.name, ".burden_significantly_greater_labeled_no_error_bars.pdf"), plot=p, width=10, height=7)

## Make a graph showing sorted 95% confidence limits on other burden values
sig.burden = print.data %>% filter(burden.category=="significant")

p = ggplot(
   print.data %>% filter(!is.na(other.burden.greater.adj.p.value)) %>% filter (other.burden.fraction.L95 > 0), 
   aes(
      x=accession,
      y=other.burden.maximum.likelihood,
      ymin=other.burden.fraction.L95,
      ymax=other.burden.fraction.U95,
   )
) +
   geom_crossbar(width = 0.8) +
   theme_cowplot(12) +
   panel_border(color = "black") +
   theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5)) +
   geom_hline(aes(yintercept=0), color="grey") + 
   geom_hline(aes(yintercept=1), color="grey")
p
ggsave(paste0(output.base.name, ".other.burden.confidence.limits.pdf"), plot=p, width=10, height=7)


p = ggplot(
   print.data, 
   aes(
      x=normalized.growth.rate.mean, 
      y=normalized.GFP.rate.mean, 
      color=burden.category, 
      #shape=other.burden.greater.significant, 
      shape=other.burden.two.tailed.significant, 
      label=plate.strain,
   )
) +
   scale_colour_manual(values=c("#4147F7", "#000000", "#FF6C6C")) +
   scale_alpha_manual(values=c(1, 0.3, 1)) +
   #scale_colour_manual(values=c("#009E73", "#56B4E9", "#000000")) + 
   coord_cartesian(
      xlim = c(min.plot.coord, max.plot.coord), 
      ylim = c(min.plot.coord, max.plot.coord)
   ) + 
   scale_x_continuous(breaks = seq(0,15, by=0.1)) +
   scale_y_continuous(breaks = seq(0,15, by=0.1))+
   geom_abline(intercept = the.intercept, slope = the.slope, show.legend=T, linetype = "dashed") + 
   geom_hline(aes(yintercept=1), color="grey") + 
   geom_vline(aes(xintercept=1), color="grey") +
   geom_point(aes(alpha=burden.category), size=2) + 
   theme_cowplot(12) +
   panel_border(color = "black")

p
ggsave(paste0(output.base.name, ".burden_significantly_different_no_error_bars.pdf"), plot=p, width=10, height=7)

